### ISSUE TITLE
[Feature Request] Trigger Plex refresh / rescan after conversion

### ISSUE THREAD

**Issue by SlorkMan** [Unmanic/unmanic#104]
It would be nice if the system could trigger Plex to do a (partial) rescan of the library the converted file is part of, using the Plex Api / X-Token perhaps?

(https://support.plex.tv/articles/201638786-plex-media-server-url-commands/)

Sometimes Plex is not aware of the fact that the file it has in its database is converted, wich results in an error.

**Comment by CanonCan** [comment]
Plex already supports refreshing on a folder change detection just enable that in settings in Plex

**Comment by Josh5** [comment]
Feature added with plugins system:
https://github.com/Unmanic/unmanic-plugins/commit/2c4985e2bdf838f38e42bf62214a508df566dc81
