### ISSUE TITLE
[Feature Request] - process by source file size

### ISSUE THREAD

**Issue by dwtaylornz** [Unmanic/unmanic#109]
When there are multiple source files in the processing queue, is it possible to have these processed in a particular order? - i.e. largest to smallest file size.

**Comment by Josh5** [comment]
This will not be possible at this point. Unmanic's task lists are just pointers to the file on disk. They do not store any data related to file size, etc.

The only solution would be to create a plugin that some how sorts the pending task queue based on file size. But that is not something on my radar at the point in time.

Closing this issue as there is nothing here that I can do to the Unmanic application to resolve this.
