### ISSUE TITLE
[Feature Request] Specify encoder bitrate

### ISSUE THREAD

**Issue by dglb99** [Unmanic/unmanic#110]
I think it would be great to be able to specify a target bitrate for the encoder depending on video size.  So maybe you'd have a 1080p preset and encode all your 1080p files to whatever you want that to be.  You could then have a different preset for 4k, and so on.

Or maybe an easier idea would be to just target a bitrate that is 60% the size of the original, then it should be able to scale well regardless of the video sizes I think.

**Comment by Josh5** [comment]
This is a great idea! I have added it to a project to look into in the future. Something in the advanced settings that allows us to have profiles setup would be awesome!

**Comment by Josh5** [comment]
The new encoder plugins can now do this with the custom input options.
