### ISSUE TITLE
[Feature Request] Run As A Service - Non Docker

### ISSUE THREAD

**Issue by statik1983** [Unmanic/unmanic#116]
For non-Docker installs, I would like to run Unmanic as a service.  I have attempted to create a systemd service file but I am not sure what the ExecStart file would be.  Which python file is the main executable for Unmanic?  Below is what I am working with so far. 

sudo nano /etc/systemd/system/unmanic.service

 [Unit]
 Description= Unmanic - Library Optimiser
 After=network-online.target
 StartLimitInterval=200
 StartLimitBurst=3

 [Service]
 Type=simple
 User=media
 Group=media
 WorkingDirectory=/opt/_Unmanic
 ExecStart=/usr/bin/python3.7 /opt/Unmanic/?????????
 Restart=always
 RestartSec=30

 [Install]
 WantedBy=multi-user.target

sudo systemctl enable unmanic.service
sudo systemctl start unmanic
sudo systemctl status unmanic

**Comment by cbrherms** [comment]
Looking at the docker's run file i'd have assumed it was `./service.py`

**Comment by statik1983** [comment]
That did not work.

**Comment by cbrherms** [comment]
This is what i have working for mine as a service:


```
[Unit]
Description= Unmanic - Library Optimiser
After=network-online.target
StartLimitInterval=200
StartLimitBurst=3

[Service]
Type=simple
User=plex
Group=plex
WorkingDirectory=/opt/unmanic
ExecStart=/usr/bin/python3 /opt/unmanic/unmanic/service.py
Restart=always
RestartSec=30

[Install]
WantedBy=multi-user.target
```

Had to make sure that /opt/unmanic/* was writeable by the user i'm running the service as due to it creating files on first run.

**Comment by statik1983** [comment]
I am using the same and it still fails.  All permissions are 777.  Yours is a systemd service in /etc/systemd/system right?


Process: 22054 ExecStart=/usr/bin/python3 /opt/_Unmanic/unmanic/service.py (code=exited, status=1/FAILURE) Main PID: 22054 (code=exited, status=1/FAILURE

**Comment by statik1983** [comment]
MediaServer systemd[1]: unmanic.service: Failed with result 'exit-code'.
May 20 10:09:32 MediaServer systemd[1]: unmanic.service: Main process exited, code=exited, status=1/FAILURE
May 20 10:09:32 MediaServer python3[21067]: ModuleNotFoundError: No module named 'schedule'
May 20 10:09:32 MediaServer python3[21067]:     import schedule
May 20 10:09:32 MediaServer python3[21067]:   File "/opt/_Unmanic/unmanic/service.py", line 40, in <module>
May 20 10:09:32 MediaServer python3[21067]: Traceback (most recent call last):
May 20 10:09:32 MediaServer python3[21067]: Original exception was:
May 20 10:09:32 MediaServer python3[21067]: FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_opt__Unmanic_unmanic_service.py.123.crash'
May 20 10:09:32 MediaServer python3[21067]:     os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o640), 'wb') as f:
May 20 10:09:32 MediaServer python3[21067]:   File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 145, in apport_excepthook
May 20 10:09:32 MediaServer python3[21067]: Traceback (most recent call last):
May 20 10:09:32 MediaServer python3[21067]: Error in sys.excepthook:
May 20 10:09:32 MediaServer python3[21067]: ModuleNotFoundError: No module named 'schedule'
May 20 10:09:32 MediaServer python3[21067]:     import schedule
May 20 10:09:32 MediaServer python3[21067]:   File "/opt/_Unmanic/unmanic/service.py", line 40, in <module>
May 20 10:09:32 MediaServer python3[21067]: Traceback (most recent call last):
May 20 10:09:32 MediaServer sudo[21064]: pam_unix(sudo:session): session closed for user root

**Comment by statik1983** [comment]
@cbrherms did you install as --user or the same plex user you have in your unmanic.service ?

**Comment by Josh5** [comment]
This has been included into the docs:
https://github.com/Unmanic/unmanic-documentation

Docs are currently hosted here at the time of comment: https://docs.unmanic.app/docs/installation/pip
