### ISSUE TITLE
Error while opening encoder for output stream

### ISSUE THREAD

**Issue by statik1983** [Unmanic/unmanic#117]
### Description

I am getting a lot of failures with the same error: "Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height". 

### Versions
Unmanic 0.0.1-beta7+a6d561+dirty
Linux Mint 19.3

### Installation Method Used

Manually installed and run

### Additional Information

Settings:
 Container:
  search extensions: mkv,avi,mov,ts,rmvb,mp4
  output container: .mkv
  remove subtitles: yes

 Video Encoding:
  video Codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
  Video Encoder: h264_nvenc

 Audio Encoding:
  Transcode all audio streams:
   enable audio streaming transcoding: yes
   Audio Codec: AAC
   Audio Encoder: aac
 Create a stereo Clone of Streams:
  enable audio stream cloning: yes
  audio codec: aac
  audio encoder: aac
  bitrate: 128k

**Comment by statik1983** [comment]
I switched to Output Container: .mp4 and now i'm not seeing any failures. yet...

**Comment by statik1983** [comment]
Still get the same error, but not as many as before.  What actually causes this error?

**Comment by Josh5** [comment]
This issue has been opened for some time. Unfortunately there is not enough information here to diagnose the cause.
If this is still persistent in the latest release, please provide logs and reopen.
