### ISSUE TITLE
[FEATURE REQUEST] Option to discard if converted file is larger

### ISSUE THREAD

**Issue by cbrherms** [Unmanic/unmanic#118]
After making a start on re-encoding the majority of my library, starting with one of the larger folders I had (300GB, ~350 episodes), I've come to notice a couple of seasons that have actually increased in size as the original files compression was better than what could be achieved.

As Unmanic appears to be useful project for both increasing likelihood of direct streaming due to standardisation, and reducing file size to free up space, an improvement would be if there was an option to discard the transcoded file from cache if the output is larger than input. 

This may then require the item to be flagged in the log that under current settings the source was smaller than the output so that it then doesn't attempt to rerun the transcode later.

**Comment by Josh5** [comment]
This is to be expected. Unmanic is not designed to give you that level of control over your library. It is a tool for standardising the formats. While we may often aim for a smaller file size as a result, this is not always going to be the case.

I already have intention of adding an "ignore list" to the application. This should give you the ability to do what you are asking for.

**Comment by Josh5** [comment]
There is now a plugin "Reject File if Larger than Original" available in the latest Unmanic release that handles this.

**Comment by eihns** [comment]
Thanks for your great product and this plugin. I wonder if the position matters and if, do the plugins automatically to the right spot? Or how would i know where it has to go? Or doesnt it matter?
<img width="481" alt="image" src="https://user-images.githubusercontent.com/43281991/225515441-415163f9-2bdb-4349-901f-f83c421e6b72.png">


<img width="482" alt="image" src="https://user-images.githubusercontent.com/43281991/225515417-929e0385-900d-49e0-b627-14f4cced20ee.png">
