### ISSUE TITLE
Additional audio codecs

### ISSUE THREAD

**Issue by Protektor-Desura** [Unmanic/unmanic#125]
It would be nice to have more audio codecs supported. I prefer opus codec because it makes smaller files than anything else and sounds way better at lower bitrates. Like you can get the exact same audio quality as MP3/320k or AAC/320k at Opus/192k. Also all browsers and most devices support Opus these days. All android devices support opus these days as well.
https://caniuse.com/opus
https://developer.android.com/guide/topics/media/media-formats

**Comment by Josh5** [comment]
This will be a task for creating a new plugin to support Opus audio encoding.

Issue created here:
https://github.com/Unmanic/unmanic-plugins/issues/102
