### ISSUE TITLE
MP4 files are not being processed

### ISSUE THREAD

**Issue by cyrixdx4** [Unmanic/unmanic#131]
Running latest version of the container seeing this message when the container attempts to process an mp4. At no point does the container attempt to process the file, skips over it completely.

[mov,mp4,m4a,3gp,3g2,mj2 @ 0x563da5ee7840] stream 0, timescale not set
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/library/movies/Dirty Harry (1971)/Dirty Harry [1080p].mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: mp42isomavc1
    creation_time   : 2020-05-12T10:38:20.000000Z
    title           : Dirty.Harry.1971.1080p.BluRay.H264.AC3.DD5.1
    artist          : 
    album           : 
    comment         : 
    encoder         : DVDFab 11.0.4.2
  Duration: 01:42:29.44, start: 0.000000, bitrate: 4188 kb/s
    Stream #0:0(und): Video: h264 (avc1 / 0x31637661), yuv420p(bt709), 1920x800 [SAR 1:1 DAR 12:5], 3733 kb/s, 23.98 fps, 23.98 tbr, 24k tbn, 47.95 tbc (default)
    Metadata:
      creation_time   : 2020-05-12T10:38:20.000000Z
      encoder         : JVT/AVC Coding
    Stream #0:1(und): Audio: ac3 (ac-3 / 0x332D6361), 48000 Hz, 5.1(side), fltp, 448 kb/s (default)
    Metadata:
      creation_time   : 2020-05-12T10:38:20.000000Z
    Side data:
      audio service type: main
    Stream #0:2(eng): Subtitle: dvd_subtitle (mp4s / 0x7334706D), 5 kb/s (default)
    Metadata:
      creation_time   : 2020-05-12T10:38:20.000000Z
    Stream #0:3: Video: png, rgba(pc), 640x266, 90k tbr, 90k tbn, 90k tbc (attached pic)
Multiple -c, -codec, -acodec, -vcodec, -scodec or -dcodec options specified for stream 0, only the last option '-c:v libx265' will be used.
Multiple -c, -codec, -acodec, -vcodec, -scodec or -dcodec options specified for stream 1, only the last option '-c:v libx265' will be used.
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> hevc (libx265))
  Stream #0:3 -> #0:1 (png (native) -> hevc (libx265))
  Stream #0:1 -> #0:2 (copy)
  Stream #0:2 -> #0:3 (dvd_subtitle (dvdsub) -> subrip (srt))
Subtitle encoding currently only possible from text to text or bitmap to bitmap

**Comment by Josh5** [comment]
While this is not a bug exactly (ffmpeg) is reporting that you cannot change these subtitle formats, the issue is that we don't currently have support for images based subtitles.

**Comment by cyrixdx4** [comment]
Do I need to adjust the codecs or settings at all? This is an odd problem that I don't believe I had ever encountered.

**Comment by Josh5** [comment]
I think it's both a lack of compatibility with unmanic and a complication in the way that ffmpeg handles subtitles. I would recommend playing with the addition arguments under unmanic's advanced settings and seeing if you can get it to work that way

**Comment by Josh5** [comment]
This issue was wrongly diagnosed. This is the encoder trying to encode a png stream to 265.

This is not an issue with the new encoder plugins available with the latest Unmanic release

**Comment by andrey-yantsen** [comment]
> This is not an issue with the new encoder plugins available with the latest Unmanic release

@Josh5 are you sure about this? I just had what seems to be the same issue with unmanic v0.1.1 (and h265 plugin v0.0.5)

```
ffmpeg -hide_banner -loglevel info -i /tmp/unmanic/unmanic_file_conversion-1633106715.869614/video-WORKING-4.mp4 -strict -2 -max_muxing_queue_size 2048 -map 0:v:0 -map 0:a:0 -map 0:v:1 -c:v:0 copy -c:a:0 copy -c:v:1 libx265 -preset medium -crf 28 -y /tmp/unmanic/unmanic_file_conversion-1633106715.869614/video-1633106715.869607-WORKING-6.mp4

...

Stream mapping:
   Stream #0:0 -> #0:0 (copy)
   Stream #0:1 -> #0:1 (copy)
   Stream #0:2 -> #0:2 (png (native) -> hevc (libx265))

...

[mp4 @ 0x556d86e3bb00] Could not find tag for codec hevc in stream #2, codec not currently supported in container
Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
Error initializing output stream 0:2 --
encoded 0 frames
Conversion failed!
```

**Comment by Josh5** [comment]
Yea. I have not had a chance to update that plugin this week. Can you open an issue on the plugins GitHub page?

**Comment by andrey-yantsen** [comment]
@Josh5 Done, thanks. Unmanic/unmanic-plugins#122
