### ISSUE TITLE
Jobs finish, but don't always transition to "completed tasks"

### ISSUE THREAD

**Issue by kythorn** [Unmanic/unmanic#143]
### Description

My instance sometimes gets into a state where workers "finish", but never show up as a success or a failure.  I have looked in the output cache, and they seem to have be 'done'. I am not sure why they fail to be moved out and logged as a success (or a failure, if it failed).

This doesn't always happen, but when it does happen, it happens to every job, even if I restart the container. The only way I have been able to resolve it is to stop the container, delete the unmanic.db.* files, and restart it.

### Steps to Reproduce

Start container. Let it process. Eventually, this starts to happen. I don't specifically know how to trigger it, but I can say it doesn't seem specific to the file being processed, as after deleting the database and restarting that file always finishes fine.

**Expected behavior:** 

All workers completing result in either a successful or 'failed' completed task. Successful files are copied out of the cache replacing the input file.

**Actual behavior:** 

Workers run, but the results just vanish. Nothing in the completed tasks list, and the output mkvs just sit in the cache directory.

**Reproduces how often:** [What percentage of the time does it reproduce?] I am not able to run unmanic for longer than a day without this happening.

### Versions

0.0.1+25fc87e

The version can be found at the footer of the WebUI. Also, please include the OS details and what version you are running
(e.g. `cat /etc/os-release`).

### Installation Method Used

I use the docker image josh5/unmanic:latest

At this time, that is digest b77135832093c092c1e51958894bf8c645d1251a63cd99b55f0c2cab672b80ff

Manually installed and run or run through Docker?

Docker

### Additional Information

Any additional information, configuration or data that might be necessary to
reproduce the issue.

I run unmanic in docker under WSL2 on a Win10 machine, targetting a library on my synology NAS mounted over CIFS.

I have tried 3 different 'host' computers, all exhibit the same behavior within a day of the container being started.

**Comment by MRobi1** [comment]
I'm seeing this exact same thing
Version - 0.0.1+95b3646

**Comment by cbrherms** [comment]
I'm now seeing the same thing also.
This is the first time this has happened, but is quite consistent now and at present the last 10 tasks have "finished" but not transferred and not appeared on completed list as either fail or complete.

The only thing that has recently changed that could potentially affect this was the fact I started to make hardlinks within my transcodes folder to files that I wanted to transcode, rather than pointing at my entire movie library.
The first job completed, but everything after that did not.

**Comment by Josh5** [comment]
> I'm now seeing the same thing also.
> This is the first time this has happened, but is quite consistent now and at present the last 10 tasks have "finished" but not transferred and not appeared on completed list as either fail or complete.
> 
> The only thing that has recently changed that could potentially affect this was the fact I started to make hardlinks within my transcodes folder to files that I wanted to transcode, rather than pointing at my entire movie library.
> The first job completed, but everything after that did not.
> I wouldn't be surprised if in the background the above people are using hardlinks on some files also? As this is a potential situation if files are still being seeded etc.
> 
> Version: 0.0.1+25fc87e
> OS: Ubuntu 18.04.4 LXC on proxmox, source files on NFS share
> Install method: manually - ran as service
> 
> Output from systemd:
> ```
> Jan 18 01:22:24 plex python3[9148]: Starting migrations
> Jan 18 01:22:24 plex python3[9148]: There is nothing to migrate
> Jan 18 01:52:25 plex python3[9148]: Exception in thread PostProcessor:
> Jan 18 01:52:25 plex python3[9148]: Traceback (most recent call last):
> Jan 18 01:52:25 plex python3[9148]:   File "/usr/lib/python3.6/shutil.py", line 550, in move
> Jan 18 01:52:25 plex python3[9148]:     os.rename(src, real_dst)
> Jan 18 01:52:25 plex python3[9148]: OSError: [Errno 18] Invalid cross-device link: '/tmp/unmanic/unmanic_file_conversion-1610932945.4042923/Knives Out (2019) - [Bluray-1080p]-1610932945.4043047.mkv' -> '/mnt/DATA/Media/transcode/Knives Out (2019)/Knives Out (2019) - [Bluray-1080p].mkv'
> Jan 18 01:52:25 plex python3[9148]: During handling of the above exception, another exception occurred:
> Jan 18 01:52:25 plex python3[9148]: Traceback (most recent call last):
> Jan 18 01:52:25 plex python3[9148]:   File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
> Jan 18 01:52:25 plex python3[9148]:     self.run()
> Jan 18 01:52:25 plex python3[9148]:   File "/var/lib/plexmediaserver/.local/lib/python3.6/site-packages/unmanic-0.0.1.dev11-py3.6.egg/unmanic/libs/postprocessor.py", line 132, in run
> Jan 18 01:52:25 plex python3[9148]:     self.post_process_file()
> Jan 18 01:52:25 plex python3[9148]:   File "/var/lib/plexmediaserver/.local/lib/python3.6/site-packages/unmanic-0.0.1.dev11-py3.6.egg/unmanic/libs/postprocessor.py", line 159, in post_process_file
> Jan 18 01:52:25 plex python3[9148]:     shutil.move(cache_path, destination_data['abspath'])
> Jan 18 01:52:25 plex python3[9148]:   File "/usr/lib/python3.6/shutil.py", line 564, in move
> Jan 18 01:52:25 plex python3[9148]:     copy_function(src, real_dst)
> Jan 18 01:52:25 plex python3[9148]:   File "/usr/lib/python3.6/shutil.py", line 263, in copy2
> Jan 18 01:52:25 plex python3[9148]:     copyfile(src, dst, follow_symlinks=follow_symlinks)
> Jan 18 01:52:25 plex python3[9148]:   File "/usr/lib/python3.6/shutil.py", line 121, in copyfile
> Jan 18 01:52:25 plex python3[9148]:     with open(dst, 'wb') as fdst:
> Jan 18 01:52:25 plex python3[9148]: PermissionError: [Errno 13] Permission denied: '/mnt/DATA/Media/transcode/Knives Out (2019)/Knives Out (2019) - [Bluray-1080p].mkv'
> Jan 18 01:52:25 plex python3[9148]: [I 210118 01:52:25 __init__:465] Running job Every 30 minutes do scheduled_job() (last run: [never], next run: 2021-01-18 01:52:24)
> Jan 18 02:22:36 plex python3[9148]: [I 210118 02:22:36 __init__:465] Running job Every 30 minutes do scheduled_job() (last run: 2021-01-18 01:52:36, next run: 2021-01-18 02:22:36)
> ```

The log you provided look like an issue with the way unmanic is able to read or write to your library. That could be incorrectly set permissions on the files, incorrectly set permissions on the mount or it could be that the shutil module does not handle hard links for some reason.

Could you try using changing back to not using hard links and see if the issue persists?

Could you also provide you systems unit?

**Comment by SkinnySkelly** [comment]
Same issue here. Just randomly started happening. I am using a network share that unmanic is reading from. But for about a week before the issue arose it was perfectly fine.

**Comment by Hime0698** [comment]
Same issue in the LinuxServer Docker image on Unraid....

Tried Deleting the unmanic.db files and also rebooting, re-installing, clearing appdata and then re-installing.

Can't seem to fix it, or at least not more than temporarily or inconsistently

**Comment by Hime0698** [comment]
Issue seemed to be fixed, but now seems to be back, Docker log contains:

```
Exception in thread PostProcessor:
Traceback (most recent call last):
File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
self.run()
File "/usr/local/lib/python3.8/dist-packages/unmanic/libs/postprocessor.py", line 126, in run
self.post_process_file()
File "/usr/local/lib/python3.8/dist-packages/unmanic/libs/postprocessor.py", line 272, in post_process_file
os.rmdir(task_cache_directory)
OSError: [Errno 39] Directory not empty: '/tmp/unmanic/unmanic_file_conversion-1631693305.1320677'
```

**Comment by Josh5** [comment]
What versions are you running to get these errors?

@kythorn , @MRobi1 @cbrherms  - Your three reports are now on such old versions of Unmanic that I cannot possibly provide you with any support. Could you please update Unmanic and let me know if you still have an issue?

@SkinnySkelly , @Hime0698 I need to know what versions you are running on also. If you are having problems with Unmanic, could you please open separate issues and supply all the requested information.

**Comment by Hime0698** [comment]
This seems to have been fixed with the latest update a couple of days ago. at least for me.

**Comment by Josh5** [comment]
Closing issue because either the report is out dated or resolved

**Comment by gotbletu** [comment]
just started using unmanic today, had the same issue.
i checked the logs, it was a write permission issue

```
podman run -ti -d \
  --name=unmanic \
  -e PUID=1000 \
  -e PGID=1000 \
  -p 8888:8888 \
  -v /media/bravo/unmanic/config:/config \
  -v /media/alfa/unmanic_watch:/library \
  -v /media/bravo/unmanic/cache:/tmp/unmanic \
  -v /media/bravo/unmanic/media:/media \
  josh5/unmanic:latest
```
only /tmp/unmanic folder has proper write permissions once it is mounted on the host machine
```
ls -la 
drwxrwxr-x /config
drwxrwxrwx /tmp/unmanic
drwxrwxr-x /library
drwxrwxr-x /media
```
you do **not** have write permission in **/library** once is mounted on the host machine. Or any other folder besides the /tmp/unmanic, so you will not be able to delete or move anything with the mover_v2 plugin.

## quick solution for other people reading this, all you gotta do is allow the folders you using with mover_v2 plugin to have write permissions
```
chmod -R 777 /media/alfa/unmanic_watch       # my /library mount
chmod -R 777 /media/bravo/unmanic/media      # my /media mount where all the completed files are moved to
```

P.S: im using Ubuntu Server 20.04 if that matters
5.4.0-110-generic x86_64 x86_64 x86_64 GNU/Linux

**Comment by Josh5** [comment]
For a little context. The docker image has a startup script that will set the permissions of the Unmanic config directory and the default /tmp/unmanic directory. It does not modify the permissions of any directories that unmanic is not 100% in charge of so as to avoid messing up peoples libraries.
