### ISSUE TITLE
ffmpeg not up to date

### ISSUE THREAD

**Issue by keichitokuna** [Unmanic/unmanic#144]
### Description

ffmpeg is not up to date :
```
[libx265 @ 0x561b78c81840] Unknown option: "allow-non-conformance.
[libx265 @ 0x561b78c81840] Unknown option: scenecut-aware-qp.
[libx265 @ 0x561b78c81840] Unknown option: scenecut-window.
[libx265 @ 0x561b78c81840] Invalid value for fades: 1".
x265 [info]: HEVC encoder version 3.2.1+1-b5c86a64bbbe
```
(Latest: 3.4)

### Steps to Reproduce

I did a fresh install of unmanic inside a Docker container on UNRAID.
Correctly map the volumes movies/tv/tmp.

Video encoding set to HEVC / libx265
Audio encoding disable

Advancing option as follow : 
`-c:v libx265 -c:a copy -preset slow -crf 23 -profile:v main10 -x265-params "allow-non-conformance=1:wpp=1:tu-intra-depth=1:tu-inter-depth=1:cutree=1:early-skip=1:limit-refs=3:cu-lossless=1:aq-mode=1:b-intra=1:constrained-intra=1:rc-lookahead=72:rc-grain=1:weightb=1:weightp=1:deblock=0,0:sao=1:sao-non-deblock=1:selective-sao=4:subme=7:me=3:rect=1:amp=1:rd=4:psy-rd=0.8:psy-rdoq=1.80:rdoq-level=1:signhide=1:temporal-mvp=1:strong-intra-smoothing=1:bframes=8:ref=4:b-adapt=2:qcomp=0.7:cbqpoffs=-1:crqpoffs=-1:qpmax=54:qpmin=0:analyze-src-pics=1:no-fast-intra=1:pass=3:stats=1:analysis-reuse-file=1:multi-pass-opt-analysis=1:multi-pass-opt-distortion=1:opt-qp-pps=1:opt-ref-list-length-pps=1:multi-pass-opt-rps=1:scenecut-aware-qp=1:scenecut-window=650:fades=1"`

**Expected behavior:** 
A clean encode.

**Actual behaviour:**

```
[libx265 @ 0x561b78c81840] Unknown option: "allow-non-conformance.
[libx265 @ 0x561b78c81840] Unknown option: scenecut-aware-qp.
[libx265 @ 0x561b78c81840] Unknown option: scenecut-window.
[libx265 @ 0x561b78c81840] Invalid value for fades: 1".
x265 [info]: HEVC encoder version 3.2.1+1-b5c86a64bbbe
x265 [info]: build info [Linux][GCC 7.5.0][64 bit] 8bit+10bit+12bit
x265 [info]: using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX
x265 [warning]: --multi-pass-opt-analysis doesn't support refining analysis through multiple-passes; it only reuses analysis from the second-to-last pass to the last pass.Disabling reading
x265 [info]: Main profile, Level-4 (Main tier)
x265 [info]: Thread pool created using 4 threads
x265 [info]: Slices                              : 1
x265 [info]: frame threads / pool features       : 2 / wpp(15 rows)
x265 [error]: can't open stats file 1.temp
x265 [error]: Analysis 2 pass: failed to open file 1.temp
[libx265 @ 0x561b78c81840] Cannot open libx265 encoder.
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
Conversion failed!
```

**Reproduces how often:** 
Always did that

### Versions

UNRAID OS 6.8.3
Unmanic Version - 0.0.1+95b3646 

### Installation Method Used

Docker installation with Community Application of UNRAID

### Additional Information

I dont think there is more.
I try the same command :
`-c:v libx265 -c:a copy -preset slow -crf 23 -profile:v main10 -x265-params "allow-non-conformance=1:wpp=1:tu-intra-depth=1:tu-inter-depth=1:cutree=1:early-skip=1:limit-refs=3:cu-lossless=1:aq-mode=1:b-intra=1:constrained-intra=1:rc-lookahead=72:rc-grain=1:weightb=1:weightp=1:deblock=0,0:sao=1:sao-non-deblock=1:selective-sao=4:subme=7:me=3:rect=1:amp=1:rd=4:psy-rd=0.8:psy-rdoq=1.80:rdoq-level=1:signhide=1:temporal-mvp=1:strong-intra-smoothing=1:bframes=8:ref=4:b-adapt=2:qcomp=0.7:cbqpoffs=-1:crqpoffs=-1:qpmax=54:qpmin=0:analyze-src-pics=1:no-fast-intra=1:pass=3:stats=1:analysis-reuse-file=1:multi-pass-opt-analysis=1:multi-pass-opt-distortion=1:opt-qp-pps=1:opt-ref-list-length-pps=1:multi-pass-opt-rps=1:scenecut-aware-qp=1:scenecut-window=650:fades=1"`
on my Macbook Pro with ffmpeg version 4.3.1 with no issue.

Thank you for reading !
And thanks for the amazing work !

K.

**Comment by Josh5** [comment]
Hey. Thanks for the detailed report.

I did heed the comment regarding the outdated base image and I've updated the build process to pull any changes from the linuxserver FFMPEG base image prior to building the rest of the Unmanic image.

I didn't test this until after I had made the latest changes, but I did notice something a little odd. Perhaps it is a lack of understanding on my part...
In your "advanced options" posted above, you included the `-c:v libx265 -c:a copy`. Unmanic reads the files and determines automatically what streams need to be encoded etc. So this part should not be required.

At any rate, in the latest build available on the staging branch, I have added the following to my "Custom FFMPEG Options" under the advanced settings tab:
```
-preset slow -crf 23 -profile:v main10 -x265-params "allow-non-conformance=1:wpp=1:tu-intra-depth=1:tu-inter-depth=1:cutree=1:early-skip=1:limit-refs=3:cu-lossless=1:aq-mode=1:b-intra=1:constrained-intra=1:rc-lookahead=72:rc-grain=1:weightb=1:weightp=1:deblock=0,0:sao=1:sao-non-deblock=1:selective-sao=4:subme=7:me=3:rect=1:amp=1:rd=4:psy-rd=0.8:psy-rdoq=1.80:rdoq-level=1:signhide=1:temporal-mvp=1:strong-intra-smoothing=1:bframes=8:ref=4:b-adapt=2:qcomp=0.7:cbqpoffs=-1:crqpoffs=-1:qpmax=54:qpmin=0:analyze-src-pics=1:no-fast-intra=1:pass=3:stats=1:analysis-reuse-file=1:multi-pass-opt-analysis=1:multi-pass-opt-distortion=1:opt-qp-pps=1:opt-ref-list-length-pps=1:multi-pass-opt-rps=1:scenecut-aware-qp=1:scenecut-window=650:fades=1"
```

With my sample video of Big Buck Bunny (https://drive.google.com/uc?id=1qAYTFtEwfCcgFjLuPCoJJGWwzYki8SbG&authuser=0&export=download) it transcoded successfully with these params.


Are you able to retest with these changes on your system and get back to me?

**Comment by keichitokuna** [comment]
> Hey. Thanks for the detailed report.

Hello Josh,

Thank you for your time !


> I didn't test this until after I had made the latest changes, but I did notice something a little odd. Perhaps it is a lack of understanding on my part...
> In your "advanced options" posted above, you included the `-c:v libx265 -c:a copy`. Unmanic reads the files and determines automatically what streams need to be encoded etc. So this part should not be required.

Indeed.
This is not odd, just my mistake ! :)


> With my sample video of Big Buck Bunny (https://drive.google.com/uc?id=1qAYTFtEwfCcgFjLuPCoJJGWwzYki8SbG&authuser=0&export=download) it transcoded successfully with these params.
> 
> Are you able to retest with these changes on your system and get back to me?

Wth Community Application Tab in UNRAID, i can only install version 0.0.1+63e0bca, which seems to be the latest one.
I am no expert with Docker, so i did not really know how to push the 0.0.2 you just release.

When i will se an update, i test it and come back to you, thank you !

**Comment by Josh5** [comment]
Did you manage to find how to update the application.
Sorry I am unable to help you with managing your server.

I'm closing this issue for now and assuming that has resolved your problem. If it has not, feel free to re-open.
