### ISSUE TITLE
TS File conversion error - No such file or directory

### ISSUE THREAD

**Issue by samcro1967** [Unmanic/unmanic#145]
### Description

Not able to process TS files.  Log shows the following:

{'error': {'code': -2, 'string': 'No such file or directory'}}

I am able to convert the file manually using handbrake and both the TS and MP4 file play as expected.

### Steps to Reproduce

1. Put a TS file in the Library Path
2. Wait for the auto scan to process the file
3. Review the logs to identify the error

**Expected behavior:** [What you expect to happen]
File is converted to mp4

**Actual behavior:** [What actually happens]
File is not converted

**Reproduces how often:** [What percentage of the time does it reproduce?]
100% of the time

### Versions

The version can be found at the footer of the WebUI. Also, please include the OS details and what version you are running
(e.g. `cat /etc/os-release`).

Docker host:  Microsoft Windows [Version 10.0.19042.685]
Docker version 19.03.5, build 633a0ea
Docker Container OS:  VERSION="18.04.5 LTS (Bionic Beaver)"
Unmanic:  Version - 0.0.1+95b3646

### Installation Method Used

docker create --name=unmanic -e TZ=America/Chicago -e PUID=0 -e PGID=0 -p 8111:8888 -v C:\Users\user\Documents\Docker\unmanic\config:/config -v xbmctv:/library -v C:\Users\user\Documents\Docker\unmanic\cache:/tmp/unmanic josh5/unmanic:latest

### Logs
```
2020-12-24T11:58:56:ERROR:Unmanic.PostProcessor - [FORMATTED] - Exception in method write_history_log - ("/library/Rachael Ray (2006)/Season 15/Rachael Ray (2006) - S15E67 - Rachael Has Got a Feast of Holiday Snacks Today; She's Serving Up Eggplant Croquettes Fried Stuffed Sage Leaves and Artichokes.mp4", {'error': {'code': -2, 'string': 'No such file or directory'}})
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/unmanic/libs/postprocessor.py", line 219, in write_history_log
    destination_file_probe = self.ffmpeg.file_probe(destination_data['abspath'])
  File "/usr/local/lib/python3.6/dist-packages/unmanic/libs/ffmpeg.py", line 156, in file_probe
    probe_info = unffmpeg.Info().file_probe(vid_file_path)
  File "/usr/local/lib/python3.6/dist-packages/unmanic/libs/unffmpeg/info.py", line 55, in file_probe
    return cli.ffprobe_file(vid_file_path)
  File "/usr/local/lib/python3.6/dist-packages/unmanic/libs/unffmpeg/lib/cli.py", line 67, in ffprobe_file
    raise FFProbeError(vid_file_path, info)
unmanic.libs.unffmpeg.exceptions.ffprobe.FFProbeError: ("/library/Rachael Ray (2006)/Season 15/Rachael Ray (2006) - S15E67 - Rachael Has Got a Feast of Holiday Snacks Today; She's Serving Up Eggplant Croquettes Fried Stuffed Sage Leaves and Artichokes.mp4", {'error': {'code': -2, 'string': 'No such file or directory'}})
```

### Additional Information

Any additional information, configuration or data that might be necessary to
reproduce the issue.

**Comment by Josh5** [comment]
It this point in time, windows is not a supported OS.

There may be an issue with the filesystem or the paths that the python module is not designed to handle. I am not willing to test these things on a Windows OS.

From the log, it appears to me that the file failed to convert prior to that error showing. It looks like nothing was written to the cache.

Another possibility is the paths of the file is not recognized in the cache after it has completed being converted.

Feel free to diagnose the issue further and provide a PR for adding support on windows.

For now I will mark this as won't fix.

**Comment by Josh5** [comment]
Closing as there has been no progression for over 6 months
