### ISSUE TITLE
Temp Data Left Behind on Failed Conversion

### ISSUE THREAD

**Issue by impalaguy1230** [Unmanic/unmanic#148]
### Description

Temporary data is left behind on failed conversion

### Steps to Reproduce

1. Check logs for failed conversions
2. Check temp folder
3. Must restart container for temp folder to automatically clear
4. However this starts the process of Unmanic trying to convert them and filling up disk again.

**Expected behavior:**

When a file fails to convert the file and folder should be deleted.

**Actual behavior:**

Temp files and folder are being left being, filling up cache disk.

**Reproduces how often:** 100%

### Versions

Version - 0.0.1+95b3646
Unraid 6.9.0-rc2

### Installation Method Used

Unraid/Docker

### Additional Information

I have a dedicated 500gb SSD setup as a cache disk for download unpacking and transcoding.  As well as a number of movies that are failing to convert.  The temp cache directory grows to 300-400gb before Unmanic gives up on trying to convert these 10 or so movies over and over again.

**Comment by Josh5** [comment]
I've begun adding a feature this week that will prevent failed transcodes being added to the task list again.
That will partially solve your issue.

I will get back to this cleanup of cached files another time.

**Comment by Josh5** [comment]
Since commit 785aef2 the post-processor now cleans up the cache directory when a task is complete. This will only not happen if there is a bug with Unmanic and the post-processor is not run for some reason.

I have also fixed a bug that caused the library scanner to re-add failed conversions into the task queue again.
