### ISSUE TITLE
When running for a long time, tmp folder is filled with empty folders

### ISSUE THREAD

**Issue by sttaelma** [Unmanic/unmanic#156]
when a conversion is finished, and the file is cut-pasted to the source folder (and the source file is deleted), the conversion folder stays.

in time and after a lot of conversions, the drive is filled with empty folders

is it possible to delete these folders at the end of each cycle?

**Comment by Josh5** [comment]
I could possibly look into this.
These directories are cleared out  whenever unmanic starts. They do not take up that much space.

**Comment by Josh5** [comment]
Some changes were made in v0.0.3 that may fix this. Could you please test this and get back to me?

**Comment by Josh5** [comment]
Since commit 785aef2a the post-processor now cleans up the cache directory when a task is complete. This will only not happen if there is a bug with Unmanic and the post-processor is not run for some reason.
