### ISSUE TITLE
Workers not showing up

### ISSUE THREAD

**Issue by CRMad** [Unmanic/unmanic#158]
I have noticed this for some time now but am just now putting a comment in about it. I normally use 3 workers and they all show up for some time, then I only see 2, then 1, and finally 0. However, they are all still working doing their work. At some point they will all show up again, but that could be weeks or even months before they do. Hopefully this is something that can be fixed.

**Comment by Josh5** [comment]
Could you give me more info.
What browser are you using?
Do you leave the browser open all the time?
How is Unmanic installed?

Without this information, I cannot do anything sorry.

**Comment by Josh5** [comment]
Closing as it's been over a month with no response
