### ISSUE TITLE
Unmanic not processing folders with apostrophe 

### ISSUE THREAD

**Issue by gacpac** [Unmanic/unmanic#159]
Look I'm trying re-encode a folder located in 

/tv/Grey's Anatomy

Unmanic doesn't like the way of how the folder looks. Could this be improved?

**Comment by Josh5** [comment]
I am unable to reproduce this with the latest code in the master branch.


![2021-04-01_18-57](https://user-images.githubusercontent.com/8370197/113250074-4de2ab00-931c-11eb-8808-f27c1eba7d52.png)
![2021-04-01_18-56](https://user-images.githubusercontent.com/8370197/113250087-50dd9b80-931c-11eb-8d0a-884fbf06f44b.png)

**Comment by gacpac** [comment]
I'm using the staging branch. 

Maybe the file itself will work, but try with a folder. Look it won't allow me to select the folder "DC's Legends of Tomorrow"


![image](https://user-images.githubusercontent.com/47924627/113376803-92803d80-9340-11eb-9bb4-8c5baf2871a4.png)

**Comment by Josh5** [comment]
I used a file inside the folder "Greys Anatomy" and it worked fine.

**Comment by Josh5** [comment]
Perhaps you could create a video showing the issue?
Also logs are really useful. Could you post your logs at the time of the fault and your configuration of how you are running Unmanic (as requested in the issue template that you have not followed).

**Comment by gacpac** [comment]
For sure! Can i add it here?

**Comment by gacpac** [comment]
here is the video. 

https://user-images.githubusercontent.com/47924627/113591626-22a0da00-9602-11eb-900b-5952975f314e.mp4

**Comment by Josh5** [comment]
Ah! I see what you mean. I thought you were talking about the workers not being able to access files or directories that have apostrophes.

I'll take a look into this.

**Comment by Josh5** [comment]
Fix added in staging. Please test and get back to me if there are still issues.
Commit 0ad9d5ea15fb4b1b7b0924adaef1c2acfeee003e

**Comment by gacpac** [comment]
It's not doing it yet.  

i can browse to folders via CLI and all. but the GUI is what needs to work really. I don't know much programming but I noticed that it looks like this over cli. 

root@b4f82f5fe1cc:/library/tv# ls
"DC's Legends of Tomorrow" 

root@b4f82f5fe1cc:/library/tv# cd DC\'s\ Legends\ of\ Tomorrow/

and it's easy  to recreate, just create an empty folder for you.

**Comment by gacpac** [comment]
Nevermind just tested in staging and it's working great!!

Thanks
