### ISSUE TITLE
Worker goes beyond 100% and ends up corrupting video file.

### ISSUE THREAD

**Issue by inenting** [Unmanic/unmanic#168]
### Description

For some files (not all) the workers go over 100% while converting. This sometimes goes up to 500%.

When this happens one of two things happen:

- The file decreases in size (60mb -> 30mb) but unmanic reports the video length has tripled. Video is corrupt.
- The file increases in size substantially (50mb -> 1.8GB), this takes over 17 hours and video is still corrupt.

Original file info:

UNKNOWN
FRAME RATE: 0/0
BIT RATE:
CODED HEIGHT: 576
CODED WIDTH: 320
HEIGHT: 568
WIDTH: 320
DURATION: 207.269700 seconds

Converted file info:

UNKNOWN
FRAME RATE: 24000/1001
BIT RATE: 236395
CODED HEIGHT: 568
CODED WIDTH: 320
HEIGHT: 568
WIDTH: 320
DURATION: 1085.209125 seconds

### Steps to Reproduce

1. Choose folder with .ts files from a livestream.
2. Choose convert to .mp4 with HEVC and libx265
3. Wait

**Expected behavior:** File converts to mp4 in a normal time frime and video is not corrupt

**Actual behaviour:** Video size changes dramatically and is corrupt

**Reproduces how often:** 1 out of 15 files

### Versions

Version - 0.0.4~9a575bc
Running in Docker

### Installation Method Used

Docker

### Additional Information

Log doesn't have any useful information

**Comment by Josh5** [comment]
Do you have a sample .TS file that you could sent me?

**Comment by inenting** [comment]
I'll have to test it till I find one cause I'm not sure which one it is. How can I send it if i find one?

**Comment by Josh5** [comment]
Perhaps just uploaded it to dropbox or google drive then email me the link. Also leave a message here when you have sent the email so it doesn't just get lost in my sea of emails.

**Comment by SuberSeb** [comment]
I have the same issue on some .mkv or .ts files. Also after that I'm experiencing OOM errors, unmanic takes about 16 Gb of RAM. Seems like a bug.

**Comment by Josh5** [comment]
I have added a bunch of memory improvements over the past 4 months. Please re-tests with the latest release of Unmanic (v0.1.0 or higher).
Feel free to reopen this issue if the problem persists
