### ISSUE TITLE
unmanic.app certificate expired

### ISSUE THREAD

**Issue by groenator** [Unmanic/unmanic#173]
When I try to access unmanic.app the SSL certificate is expired. 

Exception while registering Unmanic. - HTTPSConnectionPool(host='unmanic.app', port=443): Max retries exceeded with url: /api/v1/unmanic-register (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1123)'))

**Comment by Josh5** [comment]
Should now be fixed. Thanks for reporting!
