### ISSUE TITLE
OOM errors while converting

### ISSUE THREAD

**Issue by SuberSeb** [Unmanic/unmanic#174]
Yesterday I have experienced some really bad OOM errors, so now I have to limit memory for unmanic container to 4 gigabytes. Unmanic waste about 17 gigabytes of RAM (32 gigabytes total) while I have this error. I'm using hardware acceleration with nvenc, hevc encoder. Here my custom ffmpeg options: `-vf yadif=1:-1:1 -rc:v vbr -cq:v 28 -b:v 8000k -maxrate:v 10000k`. I haven't this errors for about a month.

Syslog errors:
`Jun  6 11:44:03 kernel: CPU: 14 PID: 23987 Comm: unmanic Tainted: P           O      5.10.28-Unraid #1
Jun  6 11:44:03 kernel: Call Trace:
Jun  6 11:44:03 kernel: out_of_memory+0x3dd/0x410
Jun  6 11:44:03 kernel: mem_cgroup_out_of_memory+0x79/0xae
Jun  6 11:44:03 kernel: Memory cgroup out of memory: Killed process 23714 (unmanic) total-vm:12578992kB, anon-rss:3579404kB, file-rss:0kB, shmem-rss:3948kB, UID:99 pgtables:7232kB oom_score_adj:0
Jun  6 13:55:56 kernel: CPU: 1 PID: 9370 Comm: unmanic Tainted: P           O      5.10.28-Unraid #1
Jun  6 13:55:56 kernel: Call Trace:
Jun  6 13:55:56 kernel: out_of_memory+0x3dd/0x410
Jun  6 13:55:56 kernel: mem_cgroup_out_of_memory+0x79/0xae
Jun  6 13:55:56 kernel: Memory cgroup out of memory: Killed process 9279 (unmanic) total-vm:9903048kB, anon-rss:3174620kB, file-rss:0kB, shmem-rss:3592kB, UID:99 pgtables:6444kB oom_score_adj:0`

MediaInfo:
`General
Complete name                  : N:\video file.mkv
Format                         : Matroska
Format version                 : Version 4
File size                      : 4.45 GiB
Duration                       : 2 h 4 min
Overall bit rate               : 5 105 kb/s
Writing application            : Lavf58.45.100
Writing library                : Lavf58.45.100
ErrorDetectionType             : Per level 1
Video
ID                             : 1
Format                         : HEVC
Format/Info                    : High Efficiency Video Coding
Format profile                 : Main@L5@Main
Codec ID                       : V_MPEGH/ISO/HEVC
Duration                       : 2 h 4 min
Width                          : 1 920 pixels
Height                         : 1 080 pixels
Display aspect ratio           : 16:9
Frame rate mode                : Constant
Frame rate                     : 50.000 FPS
Original frame rate            : 100.000 FPS
Color space                    : YUV
Chroma subsampling             : 4:2:0
Bit depth                      : 8 bits
Writing library                : Lavc58.91.100 hevc_nvenc
Default                        : Yes
Forced                         : No
Audio
ID                             : 2
Format                         : AAC LC
Format/Info                    : Advanced Audio Codec Low Complexity
Codec ID                       : A_AAC-2
Duration                       : 2 h 4 min
Channel(s)                     : 2 channels
Channel layout                 : L R
Sampling rate                  : 48.0 kHz
Frame rate                     : 46.875 FPS (1024 SPF)
Compression mode               : Lossy
Default                        : Yes
Forced                         : No`

**Comment by Josh5** [comment]
Feature branching containing the required fix is merged into staging.
PR #201
