### ISSUE TITLE
Feature Request: Add ETA to Workers

### ISSUE THREAD

**Issue by davidjmorin** [Unmanic/unmanic#175]
Feature Request:

Add the ETA for transcode under workers.  

Sample
![image](https://user-images.githubusercontent.com/9400895/121461078-26dbd180-c97c-11eb-8589-3835952cbac5.png)

**Comment by shiftylilbastrd** [comment]
And perhaps a live transcode speed

**Comment by shiftylilbastrd** [comment]
Just realized this is the same as issue #101

**Comment by Josh5** [comment]
Fix/feature merged into staging branch
