### ISSUE TITLE
moving multiple selected files to pending task list is not working

### ISSUE THREAD

**Issue by robinofe** [Unmanic/unmanic#180]
### Description

when selecting more than one failed items in the completed task section, unmanic throws the following error: 
"Could not update table. Please check that Unmanic is still running."
when selection just one item everything works fine.

### Steps to Reproduce

1. open completed Task window ("see all records")
2. select more than one item
3. click options->add selected to pending task list

**Expected behavior:** selected files are moved to pending task list

**Actual behaviour:** error message: "Could not update table. Please check that Unmanic is still running."

**Reproduces how often:** always

### Versions

Version - 0.0.8~1cd1e61
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

### Installation Method Used

run through Docker in unraid

**Comment by SkinnySkelly** [comment]
Same issue here

**Comment by shiftylilbastrd** [comment]
Same

**Comment by Josh5** [comment]
Fixed with commit e50677d
