### ISSUE TITLE
WEBM Support

### ISSUE THREAD

**Issue by Protektor-Desura** [Unmanic/unmanic#181]
It would be nice to see WEBM supported since that is open source and patent free. It means that you would need to support VP8 and VP9 and AV1. You would also need to support Opus and Vorbis audio formats. All subtitles would be to be converted to WebVVT as well. All of this can be easily done with ffmpeg.

https://en.wikipedia.org/wiki/WebM
https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Containers#webm
https://developer.mozilla.org/en-US/docs/Web/API/WebVTT_API

**Comment by Josh5** [comment]
I've started working on a VP9 Plugin. 

This will end up being a supported by 1 or more Plugins:

https://github.com/Unmanic/unmanic-plugins/issues/38
