### ISSUE TITLE
not deleting files in Cache path

### ISSUE THREAD

**Issue by pazport** [Unmanic/unmanic#182]
### Description

[not deleting files in Cache path]

### Steps to Reproduce

1. [deleted files in my Cache path]
2. [restarted unmanic]
3. [after 10 movies was re-encoded the cache path filled up again. over 500G]

**Expected behavior:** [i thought that after encoding it would move the files to original folders, then delete the file in the cache path]

**Actual behaviour:** [after it as encoded it moves the files but doesn't delete, any file in my cache path]

**Reproduces how often:** [it will delete some but not all files after moving.]

### Versions

The version can be found at the footer of the WebUI. Also, please include the OS details and what version you are running
(NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal).

### Installation Method Used
 Docker

### Additional Information

i have tried to do a fresh install of this. i have a script at moment that will delete files in my cache path. if it over 200G and starts with files that are older then 5HRS. but when i stopped it other day to test. i could see it filled up fast

**Comment by Josh5** [comment]
Please provide the version of unmanic as requested.

It will also be helpful to submit docker configuration when running Unmanic as well as logs from the docker container and the unmanic.log file as this issue is unique to yourself and will need to be reproduced in order to assist you.

Thanks.

**Comment by Josh5** [comment]
Closing due to no response
