### ISSUE TITLE
Manual search doesn't work when scanner is set to 0

### ISSUE THREAD

**Issue by shiftylilbastrd** [Unmanic/unmanic#187]
### Description
When library scan schedule is set to 0 "rescan library now' function fails to start scan

### Steps to Reproduce
1. Set library scan schedule to 0
2. From pending tasks options menu select rescan library now

**Expected behavior:** [What you expect to happen]
A library scan should be initiated

**Actual behaviour:** [What actually happens]
Library scan fails to start

**Reproduces how often:** [What percentage of the time does it reproduce?]
Everytime

### Versions
0.0.9~f50e330

### Installation Method Used
Unraid Docker using Nvidia GPU

**Comment by Josh5** [comment]
Feature branching containing the required fix is merged into staging.
PR #201
