### ISSUE TITLE
Long filenames make UI items inaccessible in completed tasks 

### ISSUE THREAD

**Issue by shiftylilbastrd** [Unmanic/unmanic#189]
### Description
When there is a long path/filename the table extends out of viewable area

### Steps to Reproduce

1. File with a long path/filename completes processing

**Expected behavior:**
Filename is truncated or wrapped to keep all UI items on screen

**Actual behaviour:**
See screenshot

### Versions
0.0.9~f50e330

### Installation Method Used
Unraid Docker with Nvidia GPU

![image](https://user-images.githubusercontent.com/39231871/125202600-23609200-e229-11eb-9737-bc10569f2065.png)

**Comment by Josh5** [comment]
Fix/feature merged into staging branch
