### ISSUE TITLE
Add pause button to global workers control

### ISSUE THREAD

**Issue by mardab** [Unmanic/unmanic#193]
I'm currently in the middle of troubleshooting hardware acceleration, it would be nice to have a "pause" button, that is, a toggle to prevent workers from picking up new jobs after finishing current ones. This kind of pause would be IMHO much easier to implement, may be useful in other cases, but in case of "testing" like I do right now, it would prevent flooding completed tasks list with same error.

**Comment by Josh5** [comment]
There is scope already for this. Unmanic is currently undergoing a redesign and should come out the other side with something to pause worker processes in the near future.

Thanks for the suggestion tho.

**Comment by Josh5** [comment]
Feature branch containing the requested feature is now merged into staging.
PR #201
