### ISSUE TITLE
Add an option to ignore x265-encoded videos.

### ISSUE THREAD

**Issue by mardab** [Unmanic/unmanic#194]
In my library I already have a few videos that are x265-encoded, but are contained in mkv, just like gigabytes of x264 recordings. It would be nice to have a toggleable check to prevent adding to pending list what is not worth reprocessing.

**Comment by Josh5** [comment]
Unmanic will no longer feature FFMpeg centric. The new feature just added to the staging branch makes all FFMpeg tasks a "Plugin" to the core Unmanic function - which is to now monitoring your library and managing the execution of commands as stipulated by the configured Plugins on your installation.

At this point in time it is a bit hard to say exactly how one would fix your specific issue. There may very well be no issue if you were to move to the new version of Unmanic (currently in staging as of writing this). However, if in the next few weeks you still have this issue against the new version of Unmanic, could you please open a Plugin request over at https://github.com/Unmanic/unmanic-plugins with any details covering exactly what you would like for the Plugin to do.
