### ISSUE TITLE
'Create a stereo clone of all audio streams' not working

### ISSUE THREAD

**Issue by HitcherUK** [Unmanic/unmanic#196]
### Description

'Create a stereo clone of all audio streams' doesn't work without enabling 'Enable Audio Stream Transcoding' as well.

### Steps to Reproduce

1. 'Enable Audio Encoding' enabled
2. 'Enable Audio Stream Transcoding' disabled
3. 'Create a stereo clone of all audio streams' enabled
4. 'Rescan library now'

**Expected behavior:** Videos with surround sound tracks (and without a separate stereo track) to be re-encoded resulting in a video with the original audio tracks and a new stereo one.

**Actual behaviour:** Nothing gets re-encoded.

**Reproduces how often:** 100%

### Versions

0.0.9~f50e330
Unraid OS Version: 6.9.2

### Installation Method Used

Docker

**Comment by Josh5** [comment]
Issue opened to create Plugin for this:
https://github.com/Unmanic/unmanic-plugins/issues/34

**Comment by HitcherUK** [comment]
Many thanks.
