### ISSUE TITLE
Intel Quicksync decoding not working on 11th Gen i7

### ISSUE THREAD

**Issue by jacauc** [Unmanic/unmanic#197]
Have you read the [Code of Conduct](CODE_OF_CONDUCT.md)? By filing an Issue, you are expected
to comply with it, including treating everyone with respect: Yes

Remember that these are some guidelines, use your best judgement.

### Description

[Description of the issue]

### Steps to Reproduce

1. Follow instructions at https://www.youtube.com/watch?v=yVhw4r94ndQ exactly
2. Add videos to encode on 11th Gen i7 CPU

**Expected behavior:** Intel Quicksync transcoding utilized

**Actual behaviour:** LOG:
[AVHWDeviceContext @ 0x55a303d4fd40] libva: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[AVHWDeviceContext @ 0x55a303d4fd40] Failed to initialise VAAPI connection: -1 (unknown libva error).
Device creation failed: -5.
Failed to set value '/dev/dri/renderD128' for option 'vaapi_device': Input/output error
Error parsing global options: Input/output error

**Reproduces how often:** Every time, every file

### Versions

main and staging branches. unRaid 6.9.2

### Installation Method Used

Manually installed and run or run through Docker? Community Addons - Docker

### Additional Information

Any additional information, configuration or data that might be necessary to
reproduce the issue.

**Comment by robinofe** [comment]
I can confirm this issue!
As with some other dockers it is neccesary to downgrade the intel media driver if you have this issue. 
At least this solved it for me: 

apt install intel-media-va-driver-non-free=21.1.2+i526~u20.04

Check here for the whole article 
https://www.gitmemory.com/issue/linuxserver/docker-jellyfin/105/824998594
br

**Comment by Josh5** [comment]
> I can confirm this issue!
> As with some other dockers it is neccesary to downgrade the intel media driver if you have this issue. 
> At least this solved it for me: 
> 
> apt install intel-media-va-driver-non-free=21.1.2+i526~u20.04
> 
> Check here for the whole article 
> https://www.gitmemory.com/issue/linuxserver/docker-jellyfin/105/824998594
> br

Thanks for finding a work-around.

I cannot test this as I do not have a recent Intel PC.

What I can do is add a startup script to add fixes like this.

**Comment by robinofe** [comment]
As far as I now you have to add this manually into the command line every time you update the docker container.
Don't know any option of a startup script - although this might be maybe possible...

But to be honest, I m not sure if this fix is working anymore with the latest release...

**Comment by Josh5** [comment]
The Unmanic docker container has a call to a script that you can write and add to the /config path. If you write such a script, it could include the fix that you are talking about.

**Comment by Josh5** [comment]
I know this is not documented anywhere. I really am starting to get stretched for time to document things like this.
This is the section of the Unmanic docker image that calls your custom startup script:

https://github.com/Unmanic/unmanic/blob/0.0.9/docker/root/etc/cont-init.d/60-custom-setup-script

Basically, if you create a bash script that would be mounted into the container as `/config/startup.sh`, the container will run it.

it could contain this:

```
apt-get update
apt-get install intel-media-va-driver-non-free=21.1.2+i526~u20.04
```

**Comment by Josh5** [comment]
@robinofe I'm going to push a development branch testing the new ffmpeg build. I've read reports that it is working fine for the new intel CPUs.
Can you please test it and get back to me?

**Comment by Josh5** [comment]
I have created branch `dev-intel_gen11`

if you add this as the docker tag you can test it and get back to me.  Eg.  `josh5/unmanic:dev-intel_gen11`

Thanks.

**Comment by Josh5** [comment]
No one ever wants to test this. Why bother creating a issue for hardware dependencies/compatibility if your not wanting to test the code for it!

I'm going to merge in the branch as I have tested it on the old CPUs and it works fine.

**Comment by jacauc** [comment]
Sorry, not using unmanic anymore so can't test
