### ISSUE TITLE
Add support for multiple source folders

### ISSUE THREAD

**Issue by SpencerXZX** [Unmanic/unmanic#198]
Have you read the [Code of Conduct](CODE_OF_CONDUCT.md)? By filing an Issue, you are expected
to comply with it, including treating everyone with respect:

Yes

Remember that these are some guidelines, use your best judgement.

### Description

If I have a folder, let's call it /TVShows, and inside of that folder are three shows:

/TVShows/Show1
/TVShows/Show2
/TVShows/Show3

Show 1 & 2 are less important to me, but Show3 is one that I want to watch in full source resolution, but I want unmanic to run on Show 1 & 2. Currently there is no way to do this that I know of, my example is basic, but I would have about 15 folders that I would want to include in the unmanic scanner.

### Steps to Reproduce

See above

**Expected behavior:** [What you expect to happen]

See above

**Actual behaviour:** [What actually happens]

See above

**Reproduces how often:** [What percentage of the time does it reproduce?]

Always

### Versions

The version can be found at the footer of the WebUI. Also, please include the OS details and what version you are running
(e.g. `cat /etc/os-release`).

All

### Installation Method Used

Manually installed and run or run through Docker?

Docker

### Additional Information

Any additional information, configuration or data that might be necessary to
reproduce the issue.

**Comment by Josh5** [comment]
duplicates by #20
