### ISSUE TITLE
Out of memory crash processing large files

### ISSUE THREAD

**Issue by mikenorgate** [Unmanic/unmanic#199]
### Description

I am noticing a large amount of RAM being used by Unmanic when it is post processing large media files, if the file size is greater than the amount of RAM available then it crashes

### Versions

0.0.9+628a581

### Installation Method Used

Docker

### Additional Information

From having a look through the code (and I might be wrong, my python is a little rusty) it looks like when the post processing calculates the hash of the file, it reads the entire file into RAM

https://github.com/Unmanic/unmanic/blob/628a581764c155d1b04375f32d527443528e2883/unmanic/libs/postprocessor.py#L195

`open(data.get('file_in'), 'rb').read()` is reading the entire file into memory. I believe you would be better off with something along the lines of this to read the file in chunks
```
with open(data.get('file_in'), 'rb') as f:
    file_hash = hashlib.md5()
    while chunk := f.read(8192):
        file_hash.update(chunk)
```

**Comment by Josh5** [comment]
Right you are.

I've already implemented this fix in the development branch. It will be in staging in the next few days.

https://github.com/Unmanic/unmanic/commit/5f39078bc0a119e24dd43ea0184fa5ff6277b43a

**Comment by Josh5** [comment]
Feature branching containing the required fix is merged into staging.
PR #201
