### ISSUE TITLE
Ability to set multiple library folders when NOT using docker

### ISSUE THREAD

**Issue by scottcase** [Unmanic/unmanic#20]
It would be nice to have this ability when not using docker setup. I have this installed on a ubuntu computer that has a nvidia gpu I use for hevc encoding and would like to be able to do
/TVShows/Kids
/TVShows/Adult
without the other directories that are in TVShows

**Comment by Josh5** [comment]
It is interesting that you raise this one mentioning a nvidia GPU. The current state of the application does not yet support any hardware accelerated encoding. I woke up this morning wondering if this should be the next step. As of yet no one has mentioned it. But your use case makes a strong argument for adding support.
I'll raise the hw acceleration support as a separate issue. And hopefully I'll get around to adding this feature over the next fortnight.

**Comment by scottcase** [comment]
Hey Josh,
That would be awesome if you could add nvidia. Basically what I did was made a change in settings.py 

### Set the supported codecs (for destination)
        # TODO: Read this from ffmpeg
        self.CODEC_CONFIG = {
            "hevc": {
                "type":"video",
                "codec_long_name":"HEVC (High Efficiency Video Coding)",
                "encoder":"hevc_nvenc"
            },

and that let me use the nvidia GPU.  

I am not an expert a python at all so i am sure there is probably a better way,  I just did a search for libx265 and changed the one if found in settings.py to hevc_nvenc

**Comment by Josh5** [comment]
At this point I'm not sure if this is going to happen.
I cannot see the case for it over just creating multiple instances of Unmanic or creating symlinks on your directory structure (if not running with Docker)

**Comment by SpencerXZX** [comment]
> At this point I'm not sure if this is going to happen.
> I cannot see the case for it over just creating multiple instances of Unmanic or creating symlinks on your directory structure (if not running with Docker)

So I'm using Docker, and have about 30 folders that I want Unmanic to process. Along with those 30 folders are around 150 folders total, so I should just create 30 docker instances of Unmanic? That seems wasteful. It would be nice to be able to map the main source directory to Unmanic and then specify 
a  "specific subfolders only" checkbox in the web GUI and then you pick which folders. Please don't take this as me being unappreciative of all the hard work you've put in to Unmanic, it's great, and I thank you for it, just offering my use case up.

**Comment by Josh5** [comment]
No problem. I encourage the discussion.
In your case with Docker, would you not just map in the individual directories that you want to manage into the container's `/library` directory?
Eg.
```
/first/path:/library/first/path
/second/path:/library/second/path
```

I'm not totally against this idea. And TBH, it would not be a huge amount of work to implement (est. around 10 hours). But its just that it has been on the todo list for over 2 years and it is really low on the priorities. There are several more requested projects from supporters of the project that have easily over 6 months of development effort required and they are going to happen before this even gets a thought. I simply don't have the time.
