### ISSUE TITLE
Question: unmanic key strategy 

### ISSUE THREAD

**Issue by jacauc** [Unmanic/unmanic#202]
Hope you don't mind me asking.... 

I've been playing with unmanic with limited success, and also found tdarr.
I'm curious about what the key differences are between the two tools or how unmanic intends to achieve something tdarr cannot do?

Liking the clean interface of unmanic, but waiting for the next release to test again. Current release have a lot of failures on my media.

**Comment by Josh5** [comment]
I can't say I've used tdarr. Looks like a decent tool.

I'm open to suggestions for improvements to Unmanic. Feel free to post something here if you have a suggestion.

**Comment by jacauc** [comment]
This is a rather simple request, but I'd like to have unmanic rename the output file with a suffix to show that it's been converted already. This will also allow radarr to detect the file size change.

I tried the mover plugin, but it only applies to completely different folders.

**Comment by Josh5** [comment]
Yea sure. Open up a request on the unmanic-plugins repository for that.

**Comment by Josh5** [comment]
Closing as there is nothing here for me to do
