### ISSUE TITLE
high memory usage

### ISSUE THREAD

**Issue by jaschuu** [Unmanic/unmanic#204]
Have you read the [Code of Conduct](CODE_OF_CONDUCT.md)? By filing an Issue, you are expected
to comply with it, including treating everyone with respect:

Remember that these are some guidelines, use your best judgement.

### Description

unmanic using 15gb of memory

### Steps to Reproduce

just let it do it's thing

**Expected behavior:** [What you expect to happen]

to clear the ram after it's finished encoding?

**Actual behaviour:** [What actually happens]

does not clear the memory 

**Reproduces how often:** [What percentage of the time does it reproduce?]

after every restart

### Versions

Version - 0.0.9~f50e330

### Installation Method Used

unraid template using /dev/shm/unmanic as encoding directory

### Additional Information

Any additional information, configuration or data that might be necessary to
reproduce the issue.

**Comment by Josh5** [comment]
This has been fixed in the staging branch.
Thanks

**Comment by jaschuu** [comment]
ok i will update to that? thanks

**Comment by Josh5** [comment]
yes you do, how did you get on with this?

Closing as the reported issue has been resolved.

**Comment by jaschuu** [comment]
just installed the staging branch, i'll let you know how if goes,
but where are all the video/audio encoding settings gone?
