### ISSUE TITLE
Feature Request: Final log - show failed command

### ISSUE THREAD

**Issue by projektdotnet** [Unmanic/unmanic#207]
In the final log, show the final command that was run, useful for confirming the output of advanced FFMPEG commands

**Comment by Josh5** [comment]
is it not enough to have it at the top of the STDOUT?

**Comment by projektdotnet** [comment]
Yeah, I don't remember what the context was for this, had something to do with failed file log output but now I cannot for the life of me figure out what I meant. I'm going to close the issue.
