### ISSUE TITLE
Remux Video Files Plugin graphic does not  render

### ISSUE THREAD

**Issue by ErikM1970** [Unmanic/unmanic#218]
Have you read the [Code of Conduct](CODE_OF_CONDUCT.md)? By filing an Issue, you are expected
to comply with it, including treating everyone with respect:

Remember that these are some guidelines, use your best judgement.

### Description

Remux Video Files Plugin graphic does not render

### Steps to Reproduce

This problem manifests itself whenever that plugin is referenced (e.g., in the repository when preparing to install, in the installed plugins page, and configure plugin flow).

**Expected behavior:** 

The expected behavior is to see the graphic associated with the Remux Video Files plugin.

**Actual behaviour:**

Anywhere Unmanic shows the Remux Video plugin, the graphic does not appear, it only shows a scrolling animation..

**Reproduces how often:**

100% (I even restarted my Unraid container to confirm it wasn't a fluke).

### Versions

0.1.0~cdde886

### Installation Method Used

Running on Unraid 6.9.2 via their Docker container

### Additional Information

This is my first Github issue submit.  Please excuse any errors.  I have also attached a graphic of the issue as seen in my environment.
![Remux Video Files Plugin Example](https://user-images.githubusercontent.com/91019374/133931591-5f51b3c2-17cc-46e9-b3dd-5ed57261601e.JPG)

**Comment by Josh5** [comment]
I dont have an icon for this plugin yet.

It may be some time yet before I create an icon. I normally do them in bulk as its time consuming and not really productive to how Unmanic works
