### ISSUE TITLE
Ability to specify a folder for converted files

### ISSUE THREAD

**Issue by itimpi** [Unmanic/unmanic#22]
### Ability to specify folder for converted files

At the moment converted files simply overwrite the original.    This can make it difficult to easily distinguish which files have been converted and which have not.

It would be useful to have the converted files into a different folder.  This makes it clear which files have been converted.    It probably makes sense to have a checkbox as to whether the original file should be kept or removed.

Such a feature would also make it easy to script some standard renaming of files to reflect the conversion.

**Comment by Josh5** [comment]
Feature added with "Mover" plugin: https://github.com/Unmanic/unmanic-plugins/tree/repo/mover
