### ISSUE TITLE
Library File Monitor not working

### ISSUE THREAD

**Issue by Landelor** [Unmanic/unmanic#222]
Have you read the [Code of Conduct](CODE_OF_CONDUCT.md)? By filing an Issue, you are expected
to comply with it, including treating everyone with respect:

Remember that these are some guidelines, use your best judgement.

### Description

Library file monitor doesn't seem to be working.

### Steps to Reproduce

1. Enable the library file monitor.
2. New file gets saved to library

**Expected behavior:** Expect new file to be added to queue for processing.

**Actual behaviour:** Nothing. New files aren't being added unless a full library scan is performed.

**Reproduces how often:** Always

### Versions
0.1.0~cdde886

The version can be found at the footer of the WebUI. Also, please include the OS details and what version you are running
(e.g. `cat /etc/os-release`).

### Installation Method Used

unRAID docker.

### Additional Information

N/A

**Comment by Chrisputer** [comment]
I would like to second this as well. Running Docker-compose and The options to choose and filter are missing. Just installed this yesterday.

**Comment by Josh5** [comment]
@Landelor that sounds like a bug. Thanks for reporting

**Comment by Chrisputer** [comment]
just did a new pull this morning and I can add Plugins now. Dunno what you did. :)

**Comment by Josh5** [comment]
> just did a new pull this morning and I can add Plugins now. Dunno what you did. :)

This has nothing to do with the reported issue here

**Comment by Josh5** [comment]
@Landelor are you able to test this again with Unmanic v0.1.3?

**Comment by Landelor** [comment]
Hi @Josh5,
Still doesn't seem to be working. Had a few files go into the library this morning without being picked up by Unmanic - v0.1.3+978f68f

These are my settings for the test.

![image](https://user-images.githubusercontent.com/8555004/141704489-83f8bbba-1519-42d5-9ee8-c312e6780b30.png)

**Comment by Josh5** [comment]
Can you enable debugging and then trigger it again with one of those files?
Either touch the file to update it's timestamp or copy the file to another directory for testing.

**Comment by Landelor** [comment]
Enabled Debugging.
Added a new file to the library and there was no new log entries.
Last entry being: `INFO:Unmanic.UnmanicLogger - Debug logging enabled`

**Comment by Josh5** [comment]
Can you also check the docker container logs?

I may need to go through all of your logs. Something must be broken

**Comment by Landelor** [comment]
I don't see anything strange. Logs attache
[DockerLog.log](https://github.com/Unmanic/unmanic/files/7535966/DockerLog.log)
[unmanic.log](https://github.com/Unmanic/unmanic/files/7535968/unmanic.log)

d.

**Comment by Josh5** [comment]
What can you tell me about your config? perhaps some screenshots of your Unraid template config?
You are right, the logs are clean.
I setup a quick test myself and was able to copy a file into a library with the monitor switched on and it detected it fine... You should see something like this:

![image](https://user-images.githubusercontent.com/8370197/141726148-535a13f7-0c4b-4635-affd-2a47f8a02fbc.png)

**Comment by Landelor** [comment]
Docker Template:
![image](https://user-images.githubusercontent.com/8555004/141727397-7907e6a2-d168-47c8-8e72-05af4a04a26b.png)

**Comment by Landelor** [comment]
I've now removed and reinstalled from scratch.
Remove container. Remove appdata folder.

Interistingly it seems to be detecting the *.srt files but not the *.mkv.
Is that telling Unmanic that a file but that name has been found and not to look further, not taking the extension into consideration?

**Comment by Josh5** [comment]
Are you using hard links by any chance?

**Comment by Landelor** [comment]
I used this to setup my shares: https://trash-guides.info/Hardlinks/Hardlinks-and-Instant-Moves/ 

I don't use Torrent, so as far as I'm aware it should be hardlinks.

**Comment by Landelor** [comment]
Hey @Josh5,
This seems to be working now.

**Comment by Josh5** [comment]
Yea. Fixed with commit 8439a7667f72263a170409f416e4eb4f38b83979

**Comment by Landelor** [comment]
Awesome thanks for your work :)

**Comment by Landelor** [comment]
Another little caveat.
/library/tv still works.
/library/movies does not.
