### ISSUE TITLE
"Run scan on start" can be enabled while "Enable the library scanner" is disabled. 

### ISSUE THREAD

**Issue by dalkain** [Unmanic/unmanic#224]
Have you read the [Code of Conduct](CODE_OF_CONDUCT.md)? By filing an Issue, you are expected
to comply with it, including treating everyone with respect:
Yes.

### Description
"Run scan on start" can be enabled while "Enable the library scanner" is disabled. 
When this occurs, the "Run scan on start" option is completely hidden in the UI, but a library scan still happens on startup.

### Steps to Reproduce
1. Start Container
2. Go to Settings > Library
3. Enable "Enable the library scanner"
4. Enable "Run scan on start"
6. Disable "Enable the library scanner"
7. Submit Library settings
8. Restart the Unmanic container
9. Library scan happens on startup

### Expected behavior:
If "Enable the library scanner" is disabled, then "Run on scan start" should be completely ignored (as is implied by the setting being hidden) and no scan should occur on startup
*Just to note: I don't like this expected behavior personally (see Additional Information below), but this behavior is what is implied by how the UI currently reacts*

### Actual behavior:
The library scanner will still run on container startup even though "Enable the library scanner" is disabled and "Run scan on start" is hidden in the UI implying that it should not be enabled.

In order to see whether this setting is enabled (or change it), you must:
1. Go to Settings > Library
2. Enable "Enable the library scanner"

### Reproduces how often:
100% of the time. I also tested deploying a completely separate docker with none of my configurations or data and was able to reproduce it immediately.

### Versions
Version - 0.1.0~cdde886

### Installation Method Used
Running in Docker on Unraid 6.9.2 using the josh5/unmanic image from DockerHub

### Additional Information
Suggested behavior:
These settings should remain independent (as they currently behave), but "Run scan on start" should always be visible on the page. Clarifying text should probably also be added to explain that the setting is independent. Maybe rename the current "Enable the Library Scanner" to "Enable periodic library scan"?

I can certainly think of use cases where these settings being independent is preferred. I personally don't mind a start-up scan but I don't want my full library auto-scanning itself after any set interval, especially not when I'm also using Library Monitoring; it would only cause unnecessary processing and disk I/O.

Here's a dirty mockup of one way the library settings could be changed provide more clarity if you choose to keep these independent:
![unmanic-library-mockup](https://user-images.githubusercontent.com/34625175/134761661-73136a13-c114-4c44-86a3-253aec6a025c.png)

**Comment by Josh5** [comment]
@dalkain This is an excellent report and suggestion. Thanks!

I totally agree. And I think your suggestion for the UI settings modifications are spot on.

**Comment by Josh5** [comment]
Fixed with commit 9baefe7
