### ISSUE TITLE
Feature - Reorder or set default subtitle track based on name

### ISSUE THREAD

**Issue by KucharczykL** [Unmanic/unmanic#238]
This is a common issue with anime video files that have dual audio (English and Japanese): after I remove the English track, the default subtitle track (to be used with the English audio track) is a signs-only subtitle track. The other one, often called full subtitle track, is almost never set as the default.

**Comment by Josh5** [comment]
This already exists

**Comment by KucharczykL** [comment]
I see the plugin you mean. It says `Specify a language tag for Unmanic to try and put as 1st subtitle track.` Are you saying if I put for example `full`, it will put subtitle tracks with the metadata title "full" (case-insensitive) in them as first? And can there be more than one term, split by commas? Thank you!

**Comment by KucharczykL** [comment]
OK, I have an update: it did put the subtitle tracks with `full` in them first but unfortunately the originally first track is still set as default so it hasn't solved my issue. Would it be possible to have a checkbox `Also make the first track the default` or is that too many things for the plugin to do at once?

**Comment by KucharczykL** [comment]
Talking about MKV. Tracks (audio and subtitles, maybe video too?) can be set to "default". This is a flag that makes most players select that track when you start playing the file.

So the plugin worked (it put the second subtitle track first) but when I play the video it automatically plays the video with the second subtitle track (which has the default flag set).

See https://ffmpeg.org/ffmpeg.html#Main-options (search for `disposition`)

**Comment by KucharczykL** [comment]
This is the info from ffmpeg:
![Screenshot_20211006_215831](https://user-images.githubusercontent.com/31072879/136274493-712ba857-f150-4c71-8ba9-02fad8b4274f.png)

**Comment by KucharczykL** [comment]
Apologies if I've misunderstood but the commit that closed this issue works with audio tracks but this issue is about **subtitle** tracks thus it doesn't fix my problem. 

Additionally, even if it worked with subtitles, the plugin select tracks by language while I need to be able to select tracks by track title (because they are all in English).

**Comment by gpack5** [comment]
Bumping this since I agree with Kucharczykl reorder audio stream does not fix this issue. We would like to be able to re-order SUBTITLES based off if it has certain words in it. Like "Full", "Dialogue" or "Dialog" since those are the ones that will work for subbed watching on anime.

**Comment by mac-lucky** [comment]
+1
