### ISSUE TITLE
Downgrade 5.1/7.1/etc to 2 channel audio 

### ISSUE THREAD

**Issue by designgears** [Unmanic/unmanic#243]
Since v0.1.0 this plugin has gone missing.

**Comment by erbmur** [comment]
I too would like to see this plugin return.

**Comment by designgears** [comment]
Moved back to tdarr, pretty bummed about it, it's overly complicated for my needs.

**Comment by yajrendrag** [comment]
there's now a plugin to "add_extra_stereo_audio" which will create a 2 channel audio from one of the multichannel audio streams (you can specify language, codec, # of channels as search parameters to find the stream you want to use as the source for transcoding - or if you leave any of them blank, it will use the first audio source w/ > 4 channels as the source).  This will add the 2 channel audio, then there's another plugin in my personal repo (see the unmanic discord plugin-repos channel), "remove_audio_stream_by_channels" that will remove all audio streams with number of channels greater than a number you specify..

the new audio channel created is encoded with aac, but if you have jellyfin-ffmpeg 5.x installed in your unmanic environment, you can opt for libfdk_aac as the encoder.
