### ISSUE TITLE
BRDISK support (iso/bdmv)

### ISSUE THREAD

**Issue by jbrodriguez** [Unmanic/unmanic#248]
### Description

It doesn't scann iso or bdmv folder structures (brdisk

### Steps to Reproduce

1. Rescan a library that contains iso or bdmv files

**Expected behavior:** [What you expect to happen]
expected these files to be picked up

**Actual behaviour:** [What actually happens]
the files were not picked up for processing

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Versions
latest

### Installation Method Used
run through docker

### Additional Information

**Comment by Josh5** [comment]
What are you wanting to do with these iso files?
If I had to guess, I would say you do not have something configured to handle them.
Can you enable debugging then reproduce the issue and submit the unmani.log file? 
Thanks
