### ISSUE TITLE
Not all remote workers being utilized

### ISSUE THREAD

**Issue by nadinio** [Unmanic/unmanic#258]
### Description

Linked unmanic installations are only using a few available workers

### Steps to Reproduce

1. Link multiple unmanic install together, a remote that can receive jobs and a hub that can send jobs
2. Allow all workers to be filled up as they are available
3. The remote install will not use all available workers to process jobs

**Expected behavior:** [What you expect to happen]

All remote workers should be working on a job

**Actual behaviour:** [What actually happens]

On an install with 4 available workers I only have 3 processing a job. On another install with 8 available workers, only 2 are being utilized

**Reproduces how often:** [What percentage of the time does it reproduce?]

70-80% of the time

### Versions

The version can be found at the footer of the WebUI. Also, please include the OS details and what version you are running
(e.g. `cat /etc/os-release`).

Version 0.1.3 on Ubuntu 20.04 LTS

### Installation Method Used

Manually installed and run or run through Docker?

Docker

**Comment by Josh5** [comment]
When this happens is there a file transfer in progress?

**Comment by nadinio** [comment]
I don't believe so. I have left one of the servers on and working overnight and it seems like the number of available workers doesn't seem to be known correctly by the installation sending jobs. For a sever that had 8 workers available, it only ever used 2. It would continue to receive jobs and process them but it wouldn't ever receive more than two tasks until I somehow found what ever combination of reboots to get it working again.

It feels like a value isn't being reset somewhere. I couldn't say what but I have had a few instances of a server with 4 available workers that is linked end up receiving 0 jobs for hours until I start rebooting servers. I can't seem to figure out exactly where the issue lies. Rebooting the remote server often will not make it suddenly start receiving jobs. Rebooting the server handing out jobs may cause a few workers to get used, but often not all of the workers available.

The only (sort of) workable solution is to reboot all servers. The ones handing out the jobs and the remote servers. Then maybe all workers will be utilized for a brief period.

Even with debug logs enabled I don't see any errors or exceptions suggesting something broke or that a file is being transferred. It just seems to ignore available workers until some internal value gets reset by rebooting everything

**Comment by Josh5** [comment]
the simple way to know if the "hub", as you put it, is detecting the number of available remote workers is to enable debugging and watch the logs. As it starts up, it creates a number of "RemoteTaskManager" threads equal to the number of workers on a remote installation plus an additional one for loading the pending tasks.

My issue with this report is that, depending on the type of work you have running, you are probably running into a problem with network transfer speeds. Unmanic will only transfer one task at a time to a remote installation. There is no benefit to transferring more than one at a time as it just slows things down. So if you have remote workers finishing tasks before the main installation can send it new ones, it will never be able to use all of the available remote workers. In my very brief testing with 2-4GB file transcodes using VAAPI with a 1GB network link, I was never able to use more than 3 remote workers before my network speed bottlenecked the process.

With this in mind I need you to confirm via logs and other tests (like reducing the remote worker count to 2 or 3) that this is not just a configuration issue on your part before I can begin investigating.
