### ISSUE TITLE
File unable to be probed by FFProbe

### ISSUE THREAD

**Issue by jimcampbell100** [Unmanic/unmanic#262]
### Description

No files show in library, no status on dashboard, no metrics.

### Steps to Reproduce

Install, drop a file into the library directory.

**Expected behavior:**

Expect the GUI to indicate that there are files, and they are being worked on.

**Actual behaviour:**

Nothing

**Reproduces how often:**

Always

### Versions

Version - 0.1.3+978f68f

This is being run via docker.  Docker host OS:

> NAME="Ubuntu"
> VERSION="20.04.3 LTS (Focal Fossa)"
> ID=ubuntu
> ID_LIKE=debian
> PRETTY_NAME="Ubuntu 20.04.3 LTS"
> VERSION_ID="20.04"
> HOME_URL="https://www.ubuntu.com/"
> SUPPORT_URL="https://help.ubuntu.com/"
> BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
> PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
> VERSION_CODENAME=focal
> UBUNTU_CODENAME=focal

### Installation Method Used

docker compose

>   unmanic:
>     container_name: unmanic
>     environment:
>     - UMASK=${UMASK}
>     - PGID=${PGID}
>     - PUID=${PUID}
>     - TZ=${TZ}
>     hostname: ${DOCKERHOSTNAME}
>     image: josh5/unmanic:latest
>     logging:
>       driver: json-file
>       options:
>         max-file: ${DOCKERLOGGING_MAXFILE}
>         max-size: ${DOCKERLOGGING_MAXSIZE}
>     ports:
>     - ${UNMANIC_PORT_8888}:8888
>     restart: unless-stopped
>     volumes:
>     - ${DOCKERCONFDIR}/unmanic:/config
>     - ${DOWNLOADSDIR}/convert:/library
>     - ${DOWNLOADSDIR}/transcode:/tmp/unmanic

### Additional Information

For the purposes of this test, I put one file in the library directory.
I have verified that the permissions are set 777 on the host, and they are accessible when I access via a shell into the docker.
I see this error in my logs, after I touch the file:

> 2021-12-02T10:31:39:INFO:Unmanic.EventProcessor - [FORMATTED] - CLOSE_WRITE event detected: - /library/Jericho (2006) - S01E01 - Pilot - The First Seventeen Hours.mp4
> 2021-12-02T10:31:39:DEBUG:Unmanic.Plugin.strip_image_streams - File unable to be probed by FFProbe - '/library/Jericho (2006) - S01E01 - Pilot - The First Seventeen Hours.mp4'
> 2021-12-02T10:31:39:DEBUG:Unmanic.Plugin.encoder_video_hevc_vaapi - File unable to be probed by FFProbe - '/library/Jericho (2006) - S01E01 - Pilot - The First Seventeen Hours.mp4'

Looking online, it seems like this is probably a permissions error.
When I open a shell into the container, though, I can do this:

> root@acepc:/library# ls -la
> total 3254668
> drwxrwxrwx 2 abc  abc        4096 Dec  2 10:04  .
> drwxr-xr-x 1 root root       4096 Dec  2 10:00  ..
> -rwxrwxrwx 1 abc  abc  3332766474 Dec  2 10:31 'Jericho (2006) - S01E01 - Pilot - The First Seventeen Hours.mp4'

> root@acepc:/library# ffprobe Jericho\ \(2006\)\ -\ S01E01\ -\ Pilot\ -\ The\ First\ Seventeen\ Hours.mp4 
> ffprobe version 4.3.1-Jellyfin Copyright (c) 2007-2020 the FFmpeg developers
>   built with gcc 9 (Ubuntu 9.3.0-17ubuntu1~20.04)
>   configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-shared --disable-libxcb --disable-sdl2 --disable-xlib --enable-gpl --enable-version3 --enable-static --enable-libfontconfig --enable-fontconfig --enable-gmp --enable-gnutls --enable-libass --enable-libbluray --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libdav1d --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --arch=amd64 --enable-opencl --enable-vaapi --enable-amf --enable-libmfx --enable-vdpau --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvenc --enable-nvdec --enable-ffnvcodec
>   libavutil      56. 51.100 / 56. 51.100
>   libavcodec     58. 91.100 / 58. 91.100
>   libavformat    58. 45.100 / 58. 45.100
>   libavdevice    58. 10.100 / 58. 10.100
>   libavfilter     7. 85.100 /  7. 85.100
>   libswscale      5.  7.100 /  5.  7.100
>   libswresample   3.  7.100 /  3.  7.100
>   libpostproc    55.  7.100 / 55.  7.100
> [mov,mp4,m4a,3gp,3g2,mj2 @ 0x5569b28e7580] stream 0, timescale not set
> Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'Jericho (2006) - S01E01 - Pilot - The First Seventeen Hours.mp4':
>   Metadata:
>     major_brand     : isom
>     minor_version   : 512
>     compatible_brands: isomiso2avc1mp41
>     title           : Pilot
>     album           : Jericho, Season 1
>     genre           : Action & Adventure
>     track           : 1/22
>     disc            : 1
>     date            : 2006-09-20
>     encoder         : SMA:Jericho.2006.S01E01.1080p.BluRay.x264-INGOT
>     iTunEXTC        : us-tv|TV-14|500
>     iTunMOVI        : <?xml version="1.0" encoding="UTF-8"?><!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd"><plist version="1.0"><dict>
>                     : <key>cast</key><array>
>                     : <dict><key>name</key><string>Lennie James</string></dict>
>                     : <dict><key>name</key><string>Skeet Ulrich</string></dict>
>                     : <dict><key>name</key><string>Gerald McRaney</string></dict>
>                     : <dict><key>name</key><string>Ashley Scott</string></dict>
>                     : <dict><key>name</key><string>Brad Beyer</string></dict>
>                     : </array>
>                     : <key>screenwriters</key><array>
>                     : <dict><key>name</key><string>Stephen Chbosky</string></dict>
>                     : </array>
>                     : <key>directors</key><array>
>                     : <dict><key>name</key><string>Jon Turteltaub</string></dict>
>                     : </array>
>                     : <key>producers</key><array>
>                     : <dict><key>name</key><string>Dan Shotz</string></dict>
>                     : </array>
>                     : </dict></plist>
>                     : 
>     season_number   : 1
>     episode_sort    : 1
>     hd_video        : 2
>     media_type      : 10
>     episode_id      : Pilot
>     network         : CBS
>     show            : Jericho
>     description     : After a nuclear disaster caused by several terrorist attacks wipes out most of North America, residents of a small Kansas town have to come to terms with a very different reality.
>     synopsis        : After a nuclear disaster caused by several terrorist attacks wipes out most of North America, residents of a small Kansas town have to come to terms with a very different reality.
>   Duration: 00:40:47.68, start: 0.000000, bitrate: 10892 kb/s
>     Chapter #0:0: start 0.000000, end 628.294000
>     Metadata:
>       title           : 00:00:00.000
>     Chapter #0:1: start 628.294000, end 1030.988000
>     Metadata:
>       title           : 00:10:28.294
>     Chapter #0:2: start 1030.988000, end 1555.929000
>     Metadata:
>       title           : 00:17:10.988
>     Chapter #0:3: start 1555.929000, end 1938.728000
>     Metadata:
>       title           : 00:25:55.929
>     Chapter #0:4: start 1938.728000, end 2447.659000
>     Metadata:
>       title           : 00:32:18.728
>     Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], 9986 kb/s, 23.98 fps, 23.98 tbr, 16k tbn, 47.95 tbc (default)
>     Metadata:
>       handler_name    : FHD
>     Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 254 kb/s
>     Metadata:
>       handler_name    : Stereo
>     Stream #0:2(eng): Audio: ac3 (ac-3 / 0x332D6361), 48000 Hz, 5.1(side), fltp, 640 kb/s (default)
>     Metadata:
>       handler_name    : 5.1 Channel
>     Side data:
>       audio service type: main
>     Stream #0:3(eng): Data: bin_data (text / 0x74786574)
>     Metadata:
>       handler_name    : SubtitleHandler
>     Stream #0:4: Video: mjpeg (Progressive), yuvj420p(pc, bt470bg/unknown/unknown), 797x1130 [SAR 1:1 DAR 797:1130], 90k tbr, 90k tbn, 90k tbc (attached pic)
> Unsupported codec with id 100359 for input stream 3

I suspect this is is a config error on my part...I apologize.  I've been banging my head against the wall and thought you may have some ideas.  I have a dozen other docker containers running, using similar permissions, and they are working fine (and have been for years).

**Comment by Josh5** [comment]
I'm going through and clearing out old issues. S this still an issue for you on the latest release?

**Comment by jimcampbell100** [comment]
Yes, same error.

**Comment by Josh5** [comment]
Could you give me an update on what version you are now testing it with?

**Comment by jimcampbell100** [comment]
0.2.2+e4610b0, in a docker

**Comment by jimcampbell100** [comment]
This no longer happens with the current version of unmanic.  I'm ok to close it.
