### ISSUE TITLE
NVIDIA-SMI debug error while using x265 cpu plugin

### ISSUE THREAD

**Issue by ravage382** [Unmanic/unmanic#267]
Have you read the [Code of Conduct](CODE_OF_CONDUCT.md)? By filing an Issue, you are expected
to comply with it, including treating everyone with respect:

Remember that these are some guidelines, use your best judgement.

### Description

[Description of the issue]
Debug log being spammed with "2021-12-09T17:43:16:DEBUG:Unmanic.Session - [FORMATTED] - Exception while registering Unmanic. - invalid literal for int() with base 10: "NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running."" This error was when using the x265cpu plugin.
I also could not fully login to unmanic.  The page would redirect after signing in with patreon but would not redirect back to the main unmanic page. Installing drivers fixed both issues.
### Steps to Reproduce

1. [First Step]
Run unmanic on a ubuntu machine with a NVIDIA GPU but not install a driver.
2. [Second Step]
Enable debugging and look in log.  
3.  Try to log in.

**Expected behavior:** [What you expect to happen]
No errors 
**Actual behaviour:** [What actually happens]
Huge amount of log spam and couldn't login.
**Reproduces how often:** [What percentage of the time does it reproduce?]
It happened 100% until the driver was installed.
### Versions
0.1.3+978f68f
The version can be found at the footer of the WebUI. Also, please include the OS details and what version you are running
(e.g. `cat /etc/os-release`).
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"

### Installation Method Used

Manually installed and run or run through Docker?
Manually installed
### Additional Information

Any additional information, configuration or data that might be necessary to
reproduce the issue.

**Comment by Josh5** [comment]
Fix coming in next release
