### ISSUE TITLE
(Feature request) Remove audio streams by language - Only keep EN

### ISSUE THREAD

**Issue by rvoosterhout** [Unmanic/unmanic#273]
I would like to use the Remove audio streams by language plugin, but I have no idea what language audio streams my video files have. It would be a nice feature to only select the languages you want to keep, instead of listing all the languages you want to remove.

**Comment by rvoosterhout** [comment]
I created a list of ALL ISO language codes, if anybody wants to use it:

Remove the languages you want to keep in your video file.

ab,aa,af,ak,sq,am,ar,an,hy,as,av,ae,ay,az,bm,ba,eu,be,bn,bi,bs,br,bg,my,ca,ch,ce,ny,zh,cv,kw,co,cr,hr,cs,da,dv,dz,eo,et,ee,es,en,fo,fj,fi,fr,ff,gl,ka,de,el,gn,gu,ht,ha,he,hz,hi,ho,hu,ia,id,ie,ga,ig,ik,io,is,it,iu,ja,jv,kl,kn,kr,ks,kk,km,ki,rw,ky,kv,kg,ko,ku,kj,la,lb,lg,li,ln,lo,lt,lu,lv,gv,mk,mg,ms,ml,mt,mi,mr,mh,mn,na,nv,nd,nl,ne,ng,nb,nn,no,ii,nr,oc,oj,cu,om,or,os,pa,pi,fa,pl,ps,pt,qu,rm,rn,ro,ru,sa,sc,sd,se,sm,sg,sr,gd,sn,si,sk,sl,so,st,su,sw,ss,sv,ta,te,tg,th,ti,bo,tk,tl,tn,to,tr,ts,tt,tw,ty,ug,uk,ur,uz,ve,vi,vo,wa,cy,wo,fy,xh,yi,yo,za,zu,

**Comment by flyingrabbi** [comment]
the hero we need! cheers, that is a great substitute while waiting for your feature request gets implemented

**Comment by Josh5** [comment]
This is not a plugin I am willing to support in the official repo. This has 100% chance of constant messages telling me that the plugin has removed all audio streams from peoples files because none of the streams were properly tagged with a correct language code. This is why the current plugin exists the way that it does where you have to specify the strings to remove.

If you want to create this plugin, you have the ability to host this in your own repo and provide support to people for it.

**Comment by rvoosterhout** [comment]
Indeed this happend to me. I'm not using the plugin anymore.

**Comment by flyingrabbi** [comment]
Thanks mate, there are so many edge cases my smooth brain can't even comprehend, your answer above makes complete sense. Thinking out loud, could you use the list above (minus en), and set it to keep en and anything untagged? Doing it that way seems like it could cut down on at least properly tagged audio streams that are unwanted.

**Comment by rvoosterhout** [comment]
Yes you could try it that way, I also did. But that is also how I lost the English stream in a few movies since they were not correctly tagged. It's a risk. I'm closig this issue now, I think there is enough info for everybody to decide if they want to use it or not.
