### ISSUE TITLE
 'Reject File if Larger than Original' (v 0.0.2)  Does not mark jobs as Failed, resulting in reprocessing 

### ISSUE THREAD

**Issue by nwskier** [Unmanic/unmanic#278]
### Description

Files reject when processed is larger than original does not mark task as 'FAILED' in Task History. The behavior does not change regardless if the plugin flag: "If the final result is still larger than the original file, ignore this file in the future." is set or not. I am assuming this ignore would mean the job is marked failed, so further worker scans would not pick the file up for processing again.

Changelog for 0.0.2 states: Add postprocessor and library file test runners to mark a file as failed and prevent it from being re-added

In plugin workflow I see a Post-processor runner for File movement.. but none listed for the Post-processor Marking task success/failure runners are listed.

### Steps to Reproduce

1. Configure 'Reject File if Larger than Original' (v 0.0.2) and select to ignore file in the future
2. Process files where this plugin is triggered, original is preserved
3. Job added to task history as successful, even though the plugin preserved the original. File continuously gets picked up by library scans due to the job being marked successful. 

**Expected behavior:** [What you expect to happen]
If this plugin runs and the original is preserved, I expect the job to be marked as 'Failed" in history, so repeated scans will not attempt reencodes.

**Actual behaviour:** [What actually happens]
Job is marked successful, so with additional scans we still see x264 and the file isn't excluded.. and reprocessing started again.

**Reproduces how often:** [What percentage of the time does it reproduce?]
100% of the time

Running current releases on all components. 0.1.4~655b18b

Manually installed and run or run through Docker? Installation through pip

![image](https://user-images.githubusercontent.com/12790303/150013339-928c701c-b4a8-473e-9c34-ad96b095102d.png)

**Comment by soonic6** [comment]
Same for me. Same file will be reencode after every scan.

**Comment by soonic6** [comment]
any news on this?

**Comment by Josh5** [comment]
Have you tried the latest version?

**Comment by soonic6** [comment]
updated my container last night, looks like it work now. thanks.

**Comment by nwskier** [comment]
What versions are you running? Mine says it is up to date at 0.0.2 .
