### ISSUE TITLE
[Feature Request] Change the default `remote_library` location

### ISSUE THREAD

**Issue by stavros-k** [Unmanic/unmanic#281]
Have you read the [Code of Conduct](CODE_OF_CONDUCT.md)? By filing an Issue, you are expected
to comply with it, including treating everyone with respect:

Remember that these are some guidelines, use your best judgement.

### Description

Currently, Unmanic uses /tmp/library for remote_library directory and also uses the same dir for cache.

This means if you make this dir `tmpfs` or ram drive, when sending large files (eg. 10GB movie) it would fill a large chunk of memory, adding then the cache to transcode the same file, it might crash the system.

Ofc, someone could choose to move this to an ssd, but this will increase writes on ssd or/and slow things down.

It would be great if `remote_library` could be moved to `/remote_library`, so everyone can choose what type of storage to use.

Ofc, this is not a huge priority but a nice to have as, in docker (and linux) you can do easily
- `/tmp/unmanic` -> `tmpfs`
- `/tmp/unmanic/remote_library` -> other storage

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behaviour:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

The version can be found at the footer of the WebUI. Also, please include the OS details and what version you are running
(e.g. `cat /etc/os-release`).

### Installation Method Used

Manually installed and run or run through Docker?

### Additional Information

Any additional information, configuration or data that might be necessary to
reproduce the issue.

**Comment by Josh5** [comment]
You can solve this if you install and use Unmanic with Docker
