### ISSUE TITLE
I cannot adjust or set settings on any plugin

### ISSUE THREAD

**Issue by neilanthonystuckey** [Unmanic/unmanic#299]
### Description

I cannot adjust or set the plugins settings.  For example cannot set reumx video to say .mp4. Happening on all plugins

### Steps to Reproduce
load web gui in browser set plugin settings. Tried multiple browsers and OS

**Expected behavior:**
Have the ability to set plugin settings

**Actual behaviour:** 
does not show plugin settings

### Versions

0.1.4~655b18b

### Installation Method Used

python3 -m pip install unmanic

mkdir -p \
/usr/local/lib/systemd/system \
/opt/unmanic

chown -R myuser:mygroup /opt/unmanic

cat << EOF > /usr/local/lib/systemd/system/unmanic.service
[Unit]
Description= Unmanic - Library Optimiser
After=network-online.target
StartLimitInterval=200
StartLimitBurst=3

[Service]
Type=simple
User=myuser
Group=mygroup
Environment="HOME_DIR=/opt/unmanic"
WorkingDirectory=/opt/unmanic
ExecStart=/usr/local/bin/unmanic
Restart=always
RestartSec=30

[Install]
WantedBy=multi-user.target
EOF

systemctl enable unmanic.service
systemctl start unmanic.service

Manually installed and run or run through Docker?

manually installed

### Additional Information

Any additional information, configuration or data that might be necessary to
reproduce the issue.

PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

**Comment by neilanthonystuckey** [comment]
![no-option-to-config-plugin](https://user-images.githubusercontent.com/56261332/153920044-dc09e4cd-4822-40f6-b3cb-68b29e40aa27.png)

**Comment by Josh5** [comment]
Click the icon from the list of installed plugins

**Comment by Josh5** [comment]
The screenshot shows you clicking the info from the plugin installer. Not from the page with the list of installed plugins

**Comment by Josh5** [comment]
OK.
I'm going to also close this issue as the whole plugin config system is changed in the upcoming release. When you next update Unmanic you will see that plugin configuration now as dedicated buttons.
