### ISSUE TITLE
Suggestion: post-conversion hook or script

### ISSUE THREAD

**Issue by lesteenman** [Unmanic/unmanic#31]
After a file has been converted, I would like to tell Sonarr or Radarr (series and movie managers) to re-scan the relevant series or movie folder to detect the new file.

An implementation could be to add post-convert.sh scripts to the config folder, and call those after converting, with the relative path of the converted file as a parameter.

**Comment by Dr-Crow** [comment]
We can probably utilize some of the code that [Sickbeard Mp4 Automator](https://github.com/mdhiggins/sickbeard_mp4_automator). They already support Sonarr and Radarr. Plus they have hooks into Plex and Emby to trigger a scan of new media.

**Comment by Josh5** [comment]
This is now completed. Unmanic now has the ability to execute post-processor scripts
