### ISSUE TITLE
Plugin Request : Change Resolution

### ISSUE THREAD

**Issue by Nonobis** [Unmanic/unmanic#317]
Have you read the [Code of Conduct](CODE_OF_CONDUCT.md)? By filing an Issue, you are expected
to comply with it, including treating everyone with respect:

Remember that these are some guidelines, use your best judgement.

### Description

I would like a simple plugin to downsize resolution on video files. 
As ui a simple listbox listing avaialablesresolution 480/720/1084 should be perfect.

**Expected behavior:** Specifiy an target resolution in plugin, and then all library using this plugin downsize video to target resolution

**Actual behaviour:** None, resolution is unchanged

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

Version: [0.2.0+31f039e](https://github.com/unmanic/unmanic/releases)

### Installation Method Used

Docker

### Additional Information

None

**Comment by Josh5** [comment]
You can do this by using the advanced options of any video encoder plugin currently. But I'll look at making a dedicated plugin for this when I get time

**Comment by Josh5** [comment]
There is a new video transcoder plugin that has the ability to apply scale filters now.
