### ISSUE TITLE
[Feature request] Apply old metadata

### ISSUE THREAD

**Issue by Shadoweee77** [Unmanic/unmanic#324]
### Description

I want to use Unmanic to convert my old footage - I have quite a lot of it. I would like to keep original date and time of those videos however - is it possible?

**Expected behavior:**

Modify the date and time of finished encode to match the original one.

Used on Truenas Scale via Truecharts docker app :)

Thanks!

**Comment by Josh5** [comment]
This could be achieved with a post-processor plugin.

**Comment by Josh5** [comment]
I've created this plugin and added it to my development repo. Feel free to test it out and see if it suits your needs:
https://github.com/Josh5/unmanic.plugin.replicate_source_file_stats
