### ISSUE TITLE
Removes Dolby Vision

### ISSUE THREAD

**Issue by RiDDiX** [Unmanic/unmanic#328]
Every mkv file with dolby vision or even mp4 with dolby vision getting cleared of dolby vision.

Reproduce for me is just remove languages and subtitles, after finishing I check my mp4 / mkv file and DV (dolby vision) is also gone.

**Comment by Josh5** [comment]
Can you share details of your config. Screenshots are good.

**Comment by RiDDiX** [comment]
<img width="1661" alt="Bildschirmfoto 2022-05-02 um 22 33 36" src="https://user-images.githubusercontent.com/22412488/166323310-0e79eec4-2370-486e-bb7d-6527330cb5ef.png">
<img width="1661" alt="Bildschirmfoto 2022-05-02 um 22 34 02" src="https://user-images.githubusercontent.com/22412488/166323315-38be7197-c4cb-406a-b664-def1c0d56a79.png">

**Comment by Josh5** [comment]
This is not something that I am going to fix at this point. Someone else will need to investigate
