### ISSUE TITLE
Bug: "Submit" on Settings --> Link enables preload

### ISSUE THREAD

**Issue by fredrikbaberg** [Unmanic/unmanic#332]
### Description

On pressing "Submit" the toggles for Preload is enabled for all remote installations.

### Steps to Reproduce

1. Go to Settings
2. Go to Link
3. Press "Submit".

Assuming a remote installation has been added and has "Send tasks to this installation when workers are available" checked but (but not preload)

**Expected behavior:** Preloading should not be enabled if it wasn't before.

**Actual behaviour:** Preloading is checked for all remote installations, at least if "Send task to this installation when workers are available" was checked before the button was pressed.

**Reproduces how often:** 100%

### Versions

Version: [0.2.2+e4610b0](https://github.com/unmanic/unmanic/releases)

Browser: Microsoft Edge (Windows 11).

### Installation Method Used

Manually installed and run

**Comment by Josh5** [comment]
I think to fix this we need to modify how a link is initially configured. There can be a delay between the time a link is first created and when it is then actually ready to be configured.

I'm going to scope this fix as needing some kind block on configuring a link straight after it has been created and then a list item reload once the link has finished initialising in the background
