### ISSUE TITLE
IMPROVEMENT: Send settings to workers.

### ISSUE THREAD

**Issue by git4unrealnondev** [Unmanic/unmanic#334]
IMPROVEMENT have a button for linked workers to automatically send configurations of plugins for libraries.
IE:
Library shows has: Remuxer -> h265 cpu encode -> Re-Order audio streams

Would it be possible to have a button or just automatically copy plugin configs for a library to a worker and have it automatically run?
Would it be possible to have the worker client automatically download needed plugins and config them for that specific library?
Many thanks

**Comment by Josh5** [comment]
Yup! Sounds like a good feature

**Comment by Josh5** [comment]
I'm going to close this as the feature added does close to what was requested
