### ISSUE TITLE
“Transcode Video Files” vs other “Video Encoder…” plugins

### ISSUE THREAD

**Issue by jbishop129** [Unmanic/unmanic#361]
Have you read the [Code of Conduct](CODE_OF_CONDUCT.md)? By filing an Issue, you are expected
to comply with it, including treating everyone with respect:

Remember that these are some guidelines, use your best judgement.

### Description

I’m curious what the “Transcode Video Files” plugin should be used for vs the other “Video Encoder…” types.  The former seems to have (in my mind) simpler options to set. Is that the preferred way to re-encode h.264 and other to h.265? 

### Steps to Reproduce

1. Go to Settings… Plugins.. and you can find many options for video encoding.

**Expected behavior:** N/A just asking a question

**Actual behaviour:** N/A

**Reproduces how often:** N/A

### Versions

0.2.3~b517463

### Installation Method Used
Docker

Manually installed and run or run through Docker?
Docker

### Additional Information
N/A

**Comment by Josh5** [comment]
In the coming weeks the other plugins will be removed from the official repo. The transcode video plugin will be the only one that will combine all the features of all the other plugins. Sorry for the confusion. My recommendation is to use the new plugin and ignore the old ones for now.

**Comment by jbishop129** [comment]
Glad I asked, and thanks for the clarification! I'll switch over to it right away
