### ISSUE TITLE
Ability to pause a worker via CLI/API?

### ISSUE THREAD

**Issue by arjones85** [Unmanic/unmanic#374]
I am unable to find this feature, so I wanted to ask before putting in a feature request - 

Is there any ability to control workers via CLI? What I am wanting to do is check Plex status, and if a stream is going that is being transcoded, pause one of the Unmanic workers. When the stream is done, the worker will be resumed.

I am not seeing this ability to control Unmanic via CLI or API. Is this something that is available and I am missing it?

Thanks!

**Comment by Josh5** [comment]
Have you looked through the API documentation?

**Comment by arjones85** [comment]
> Have you looked through the API documentation?

I can't seem to find any documentation about the API on the docs website. Would you mind linking it?

Thank you!

**Comment by Josh5** [comment]
In the help and support section of the application you will find links to documentation including the API schema.
