### ISSUE TITLE
H264 to HEVC H265

### ISSUE THREAD

**Issue by joshyboyy** [Unmanic/unmanic#381]
Sometimes when encoding files from H264 to H265 the file size is larger.

Remember that these are some guidelines, use your best judgement.

### Description

[Description of the issue]

**Expected behavior:** Expect file to be smaller after file conversion

**Actual behaviour:** file is larger sometimes by very little, sometimes by gigs

**Reproduces how often:** about 50% of the time

### Versions
Version: [0.2.3~b517463](https://github.com/unmanic/unmanic/releases)

### Installation Method Used

Docker Unraid Template

**Comment by Josh5** [comment]
This is neither a bug, issue or feature request. Please seek support on discord if you need help with your configuration of a plugin.
https://unmanic.app/discord
