### ISSUE TITLE
Feature/Enhancement: Assign/Restrict worker groups to libraries

### ISSUE THREAD

**Issue by appiekap653** [Unmanic/unmanic#387]
I was thinking about a feature to assign / restrict worker groups to specific -/ multiple libraries.

let's say you want to have only one worker simultaneously doing some heavy lifting jobs on your system, but at the same time you want a second worker doing some less performance required jobs.

for example:

1st worker - transcode all video files.
2nd worker - change ASS subtitles to SRT.

At the moment I have created 2 worker groups with both the worker count set to 1.
but they both run jobs next in line at the queue, resulting in 2 workers simultaneously trans-coding files and after that 2 workers simultaneously change subtitles.

If you can assign worker groups to specific -/ multiple libraries, it will for example:

Start with utilizing 2 workers:
1 worker for trans-coding jobs and 1 worker for subtitles jobs.

After the subtitle jobs are finished, only one worker will continue to work on trans-coding jobs.
Leaving the other worker idle waiting for other jobs from libraries that need less performance required tasks.

With this option you can still process multiple things simultaneously without maxing out your system resources.

Maybe create a feature to add multiple worker groups Id's to a library, with the possibility to add them to multiple libraries.

Then when Id's are configured in a library, hand those Id's as metadata to the queue jobs. (I believe you are already doing this with the priority options, please correct me if I'm wrong)

At the queue: Test the jobs for the presence of Id's and check if the corresponding worker group is idle and ready to take the job.

I'm curious about your thoughts on this.

with regards,

Arjen Hissink

**Comment by Josh5** [comment]
This is what the tags are for. Assign different tags to the 2 libraries and then the 2 worker groups
