### ISSUE TITLE
Data Panels not working

### ISSUE THREAD

**Issue by wdavies39** [Unmanic/unmanic#393]
I'm running Unmanic in a Docker in Unraid.

It is working very well, apart from not showing Data Panels. I have installednthe Data Panels plugin, but when I try to see the data panels, I get the following message "DataTables warning: table id=history_completed_tasks_table - Invalid JSON response. For more information about this error, please see http://datatables.net/tn/1".

I'm not computer literate enough to be able to sort this out myself - could anybody please give me any suggestions of how to get the data panel back?

Thanks

Wallis

**Comment by StoneCotton** [comment]
From my understanding, it has to do with the way that the data panel is setup. I had the same issue when setting it up. Not sure if this is necessarily the correct way but it looks like order of operations matters with Data Panels. I got mine to work using the following flow:

**Worker Processing File**
-File Size Data Metrics Data Panel
-Strip all image streams from file
-Audio Encoder AAC
-Normalize AAC Audio Streams
-Reorder audio streams by language
-Video Encoder H265
-Remux Video Files

**Post-Processor**
-Normalize AAC Audio Streams
-File Size Data Metrics Data Panel

**Comment by wdavies39** [comment]
Thanks, i've moved the Data Panels plugin to be the first to be processed and that has solved the problem - Unmanic is a great programme and it's good to see the Data Panels again and see how good it is at reducing file size!

Thanks for your help

Wallis

**Comment by wdavies39** [comment]
Thanks for all your hard work, Josh. In manic is a great programme! Easy to use - I should know, I’m 76 and have 3 workers running now saving me terabytes of space!!Sent from my iPhone Walter Davies647 938 3230On Mar 20, 2023, at 4:15 PM, Josh Sunnex ***@***.***> wrote:﻿
Closed #393 as completed.
