### ISSUE TITLE
Unmanic not actually changing file

### ISSUE THREAD

**Issue by Nbr1Sniper** [Unmanic/unmanic#395]
Have you read the [Code of Conduct](CODE_OF_CONDUCT.md)? By filing an Issue, you are expected
to comply with it, including treating everyone with respect:

Remember that these are some guidelines, use your best judgement.

### Description

None of my video files change after the worker is finished. The worker will run as I assume it should then move file from temp to the cache (if I force mover to run and retry everything it still doesn’t work properly). The audio and subtitle changes I wanted aren’t processed and it seems no transcoding is actually saved. The file date and time change but nothing else. I still have multiple languages which I don’t want. 

Sub issue, how to get intel QSV to work…

**Expected behavior:** [What you expect to happen] I expected to have everything but English, Japanese, and Hebrew removed as spoken or subtitle language 

**Actual behaviour:** seems to transcode and move a file but no change. 

### Versions

The version can be found at the footer of the WebUI. Also, please include the OS details and what version you are running 
(e.g. `cat /etc/os-release`). 6.11.5 unraid and 0.2.3 of Unmanic

### Installation Method Used

Manually installed and run or run through Docker? Unraid/Docker

### Additional Information

Any additional information, configuration or data that might be necessary to
reproduce the issue.

**Comment by Josh5** [comment]
This is likely a configuration issue. Jumonto the support discord and get help there.
