### ISSUE TITLE
[Feature Request] notification via telegram

### ISSUE THREAD

**Issue by spupuz** [Unmanic/unmanic#399]
is i possible to setup in someway a notification of the start / completion of failure of file processing to telegram? Assumin to inegrate with home made script via python there are variable to pass?

**Comment by yajrendrag** [comment]
you could simply use an external worker process plugin or external post process plugin to run a bash, python, or node.js script to do your notification.. or am i misunderstanding what you're looking for?

**Comment by spupuz** [comment]
i create the following script un python and tested out of unmanic and it's working.

```
import requests

bot_token = "my_token_here"
chat_id = "my_chat_id_here"
notification_message = f"conversion of file {output_files} is finished successfully"

url = f"https://api.telegram.org/bot{bot_token}/sendMessage?chat_id={chat_id}&text={notification_message}"
response = requests.get(url)

if response.status_code == 200:
    print("Notification sent.")
else:
    print(f"Failed to send notification: {response.content}")
```

i selected:

![image](https://user-images.githubusercontent.com/1721792/235685466-b8147ac9-e255-46c6-8b0f-1e05d9a43898.png)

and there for variabile to pass and requirements:

![image](https://user-images.githubusercontent.com/1721792/235685657-ba074bf7-79dc-4091-9779-0817c2d4eb96.png)

but does not work

**Comment by spupuz** [comment]
```
2023-05-02T13:59:01:ERROR:Unmanic.PluginExecutor - [FORMATTED] - Exception while carrying out 'postprocessor.task_result' plugin runner 'postprocessor_script'

Traceback (most recent call last):

  File "/usr/local/lib/python3.8/dist-packages/unmanic/libs/unplugins/executor.py", line 256, in execute_plugin_runner

    runner(data)

  File "/config/.unmanic/plugins/postprocessor_script/plugin.py", line 345, in on_postprocessor_task_results

    cmd = build_script(settings, data)

  File "/config/.unmanic/plugins/postprocessor_script/plugin.py", line 299, in build_script

    executable = get_executable_venv_python(script_dependencies, temp_working_directory, dependency_cache_directory)

  File "/config/.unmanic/plugins/postprocessor_script/plugin.py", line 207, in get_executable_venv_python

    exec_subprocess("{} -m venv venv".format(executable), "", cwd=temp_working_directory)

  File "/config/.unmanic/plugins/postprocessor_script/plugin.py", line 181, in exec_subprocess

    raise Exception("Failed to execute command: '{}'".format(full_command))

Exception: Failed to execute command: '/usr/bin/python3 -m venv venv
```

here is the error i got

**Comment by yajrendrag** [comment]
Also, you probably want "{output_file_path}" and not "{output-files}" - see this note in the info page:
```
{output_files}

Will be replaced with a JSON object list of files generated.

Only available when Run the command for each output file created by Unmanic. is unselected.
```

**Comment by yajrendrag** [comment]
please try it the way i suggested here - https://github.com/Unmanic/unmanic/issues/399#issuecomment-1531494026

**Comment by spupuz** [comment]
> please try it the way i suggested here - [#399 (comment)](https://github.com/Unmanic/unmanic/issues/399#issuecomment-1531494026)

now the script sent the message but the name in the message is wrong:

"conversion of file {output_file_path} has finished successfully"

**Comment by spupuz** [comment]
thanks man i was able to make it work!!! great!

**Comment by yajrendrag** [comment]
Great! Glad it workedOn Tue, May 2, 2023 at 9:20 AM spupuz ***@***.***> wrote:
thanks man i was able to make it work!!! great!
