### ISSUE TITLE
Failed to fetch the list of plugin repos

### ISSUE THREAD

**Issue by tristengrant** [Unmanic/unmanic#415]
### Description

I've installed Unmanic via docker-compose on a Debian GNU/Linux machine on OMV. After setting up my library, I went to add some plugins and found none. When I click refresh, I get a "Failed to fetch the list of plugin repos." notification. If I install via a repo it says save but if I the refresh I get "Unable to update your configured repositories. Perhaps there is an error in one of the URLs?"

I copied the example docker-compose file from the Unmanic documentation and made the necessary changes.

**Comment by pgosselar** [comment]
I experienced the same thing on Ubuntu 20.04.6, both using Docker Compose and PIP (w/ Python 3.10.11.final.0) installation methods. 

@tristengrant, did you ever figure it out?

**Comment by tristengrant** [comment]
@pgosselar No. I never did figure it out.

**Comment by jaavalli** [comment]
Same issue for me. Happens same way on two different VMs (Ubuntu 22.04.3 LTS) running docker.

**Comment by regularguy01** [comment]
https://github.com/Unmanic/unmanic/issues/450

**Comment by juan11perez** [comment]
Installed in unraid. Plugin installer is empty.

**Comment by Josh5** [comment]
Should be fixed now. Reopen if you are still having issues.
