### ISSUE TITLE
[Feature Request] Library Scanning at a schedule time

### ISSUE THREAD

**Issue by Minxster** [Unmanic/unmanic#416]
Would it be possible to have a library scan triggered at a set time? I'm currently monitoring my DVR folder, and ideally I only want it to start transcoding on a night time, so there's no need to scan every X hours.

**Comment by Josh5** [comment]
Could I suggest setting a cron job to trigger the library scan?

**Comment by Minxster** [comment]
@Josh5 I'm happy to use that, do you have an example of how to achieve this? Ideally something that can be easily repeated, especially when a container image upgrade/update happens?

**Comment by Minxster** [comment]
@Josh5 I finally figured it out. It took me some time, but did track down info about the API info/doc actually being available inside UnManic itself. So I'm just posting this back, in case others come along and want a working example of how to use the API 😉

```
curl -X 'POST' \
  'http://unmanic/unmanic/api/v2/pending/rescan' \
  -H 'accept: application/json' \
  -d ''

```  
```
wget --header="accept: application/json" \
  --header="content-type: application/x-www-form-urlencoded" \
  --post-data= \
  --output-document - \
  http://unmanic/unmanic/api/v2/pending/rescan
```
