### ISSUE TITLE
All default plugin missing

### ISSUE THREAD

**Issue by gardiol** [Unmanic/unmanic#450]
Just pip-installed on my linux and there are plugins.
The .unmanic/plugins folder is empty.

**Comment by gardiol** [comment]
Reply to myself:
i cloned unmanic default repo, run the ./generate_repository.py script, moved the repo folder under "pluguins" in unmanic folder, restarted unmanic. Fixed.

Still i think they should be present in pip install.

**Comment by regularguy01** [comment]
I found it missing as well in docker on Unraid.  However the link is in the documentation. https://docs.unmanic.app/docs/configuration/plugins/adding_a_custom_plugin_repo

`https://raw.githubusercontent.com/Josh5/unmanic-plugins/repo/repo.json`

**Comment by juan11perez** [comment]
Installed in unraid. Plugin installer is empty.
Tried the above suggestions unsuccesfully
