### ISSUE TITLE
Transcode Video Files - Force transcoding even if the file is already using the desired video codec

### ISSUE THREAD

**Issue by regularguy01** [Unmanic/unmanic#454]
### Description
The .unmanic uses the original encoded file name.  Making this feature unreliable.  Most Media managers change the name of the file based on it new encoding (done by unmainic).  This allows the file to be encoded and then encoded again. 

[Description of the issue]

original file name Example:
Regular Movie [dts][h264].mp3
After unnmanic encodes 
Regular Movie [dts][h264].mkv
.unmanic file 
inside is 
{
  "video_transcoder": {
    "Regular Movie [dts][h264].mkv": "force_transcoded"
  }
}

Then the media manger runs a name change based on the new encoding
Regular Movie [dts][h264].mkv > Regular Movie [ac3][h265].mkv

However the unmainc file is  still 
{
  "video_transcoder": {
    "Regular Movie [dts][h264].mkv": "force_transcoded"
  }
}

So when the library scans it picks up 
Regular Movie [ac3][h265].mkv
because the unmanic file is still based on the first name.
{
  "video_transcoder": {
    "Regular Movie [dts][h264].mkv": "force_transcoded"
  }
}
Seem like you might just want to set just a empty .unmanic file or use just the actual movie name like "Regular Movie"

So if the plugin sees any .unmanic file it skips

### Steps to Reproduce

above

**Expected behavior:** That it sets an .unmanic file scans once based on the Force feature

**Actual behavior:** Encodes the already encoded file twice instead of once

**Reproduces how often:** every time
### Versions  latest
Version: [0.2.4~7339f8b]

The version can be found at the footer of the WebUI. Also, please include the OS details and what version you are running
(e.g. `cat /etc/os-release`).  Unraid 6.12.8

### Installation Method Used

Unraid Docker

**Comment by dhstsw** [comment]
I'd like to expand on this:
I use unmanic to download and automatically encode i h265/mkv.
If the source file is 480p it's just encoded.
If the source file is above 480p (mostly 720p and 1080p) the file is scaled to 480p and encoded in h265.
The problems arise when the source file is above 480p and already in h265/mkv: unmanic just skips it saying there are no streams to be processed, so it's not scaling it down.
Would be useful to have a flag in the h265 plugin (in my case, the nvenc one) to force it to process the file even if the stream is already in h265.
Thanks.
