### ISSUE TITLE
library scanner can pick up a file that is currently being copied.

### ISSUE THREAD

**Issue by Josh5** [Unmanic/unmanic#46]
To prevent this from happening, the application needs to test if a file is being modified prior to adding it to a queue

**Comment by blddk** [comment]
One fix for this, is to have the tmp dir on the same array as the file encoded. This will make it appear instantly in its full size on the target path after encoding.

Another fix could be to move it with .tmp extension, then just rename it to ex. .mp4 (or what ever selected) after the file has been copied.

**Comment by Josh5** [comment]
This is no longer a problem
