### ISSUE TITLE
can I specify a config location? 

### ISSUE THREAD

**Issue by OneCDOnly** [Unmanic/unmanic#480]
Hi guys, 

Just trying to work out if there's a way to specify a config path when launching the unmanic daemon. 

The only information I've found so-far is:
```
# ./unmanic --help
usage: unmanic [-h] [--version] [--manage_plugins] [--dev] [--dev-api [DEV_API]] [--port [PORT]]

Unmanic

options:
  -h, --help           show this help message and exit
  --version            show program's version number and exit
  --manage_plugins     manage installed plugins
  --dev                Enable developer mode
  --dev-api [DEV_API]  Enable development against another unmanic support api
  --port [PORT]        Specify the port to run the webserver on
```
I've installed it from PyPI, and it is writing its settings into `$HOME/.unmanic`. 

I'm building a NAS package for this, and in this particular NAS, `$HOME` can't be used by any applications. 

Any suggestions? 

Thank you for this great project. 🤓

**Comment by OneCDOnly** [comment]
Some progress: I set $HOME_DIR before starting it and now it's writing it's config there. I'll keep testing.

**Comment by Josh5** [comment]
> Some progress: I set $HOME_DIR before starting it and now it's writing it's config there. I'll keep testing. 
> 
> Hmm, it's duplicating the same tree structure it created in $HOME. 

$HOME_DIR is the way to do it at this point in time

**Comment by OneCDOnly** [comment]
Thanks @Josh5, that's working fine. 

Cheers! 🤓
