### ISSUE TITLE
Task list scrolling gets stuttering.

### ISSUE THREAD

**Issue by HenkaN94** [Unmanic/unmanic#50]
### Description
Scrolling both pending and completed tasks list with many queued/finished jobs feel very stuttering and can skip large chunks so it's hard to find the specific file you're looking for.

### Versions
Version - 0.0.1-beta4~aad4ffd 

### Installation Method Used
Both unRaid docker and manual install.

### Additional Information
With a small amount of pending jobs this isn't really a thing, however if you add a lot of items at the same time it will get really annoying.

And with potential future features like removing or changing job orders this can become an actual problem.
My personal suggestion is that you split up the list over multiple pages with a limit of like 25 or 50 items per page.

**Comment by Josh5** [comment]
Perhaps the task queue needs to start using the database.  Not sure how at this stage, but I'll look into it.

**Comment by Josh5** [comment]
This has been fixed since the database was introduced. closing
