### ISSUE TITLE
Using verison 0.2.8 (from 0.2.7) results in permission errors and fails to deploy

### ISSUE THREAD

**Issue by Retract1822** [Unmanic/unmanic#500]
### Description

After changing docker image tag to `0.2.8` from `0.2.7` Unmanic does not seem to deploy correctly, lots of permission errors in the logs (see below) but it was working fine using exactly the same deployment previously, only the tag was updated to `0.2.8`.

### Steps to Reproduce

1. Redeploy docker compose file using image 0.2.8

**Expected behavior:** It deploys correctly as has done previously

**Actual behaviour:** It does not deploy properly. It results in "Bad Gateway" when trying to browse to it and this is the log output:

```
[migrations] started

[migrations] no migrations found

/package/admin/s6-overlay-3.1.6.2/etc/s6-rc/scripts/cont-init: 20: /etc/cont-init.d/20-config: Permission denied

/package/admin/s6-overlay-3.1.6.2/etc/s6-rc/scripts/cont-init: 20: /etc/cont-init.d/30-patch-nvidia: Permission denied

/package/admin/s6-overlay-3.1.6.2/etc/s6-rc/scripts/cont-init: 20: /etc/cont-init.d/60-custom-setup-script: Permission denied

───────────────────────────────────────

  _____ __ __ _____ _____ _____ _____ 

 |     |  |  |   __|_   _|     |     |

 |   --|  |  |__   | | | |  |  | | | |

 |_____|_____|_____| |_| |_____|_|_|_|

       _____ __ __ _ __    ____  

      | __  |  |  | |  |  |    \ 

      | __ -|  |  | |  |__|  |  |

      |_____|_____|_|_____|____/ 

  Based on images from linuxserver.io

───────────────────────────────────────

To support LSIO projects visit:

https://www.linuxserver.io/donate/

───────────────────────────────────────

GID/UID

───────────────────────────────────────

User UID:    1000

User GID:    1000

───────────────────────────────────────

[custom-init] No custom files found, skipping...

s6-supervise unmanic: warning: unable to spawn ./run (waiting 60 seconds): Permission denied

[ls.io-init] done.
```

**Reproduces how often:** 100% of the time so far.

### Versions

0.2.7 = working fine.
0.2.8 = having this issue

Host OS:

```bash
PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

### Installation Method Used

Docker

### Additional Information

This has never happened before, only seems to be affected on version 0.2.8

**Comment by Josh5** [comment]
Thos has been resolved. Update to latest

**Comment by Retract1822** [comment]
Thank you it did seem to be fixed  for a bit but it appears to be back again. Do I need to use the latest tag? I try to pin my docker images where possible and it seems like when using 0.2.8 it's happening again

**Comment by Josh5** [comment]
0.2.8 will always be broken. You can either use latest or leave it on 0.2.7 until 0.2.9 is released.

**Comment by Retract1822** [comment]
> 0.2.8 will always be broken. You can either use latest or leave it on 0.2.7 until 0.2.9 is released.

Understood, thank you very much :+1:
