### ISSUE TITLE
[Feature Request] Restrict conversion to files with keywords like "remux"

### ISSUE THREAD

**Issue by millertime0503** [Unmanic/unmanic#62]
It would be handy if I could restrict unMANIC to only converting files with "remux" in the name. The bulk of my movie library is uncompressed remuxed H.264. I'd like to prioritize my CPU burn by compressing these giant uncompressed files before it goes after a WEBDL version, for instance. A WEBDL H.264 is already compressed, so re-encoding it won't be as worthwhile for storage savings/clock cycles as a remux.

**Comment by bjeanes** [comment]
Or even to prioritise by largest filesize first would make some sense.

**Comment by jfroebe** [comment]
What about giving unmanic a file containing the list of files to convert?  That way a custom order is easily done.

**Comment by Josh5** [comment]
You can restrict Unmanic with the "Path Ignore" plugin and some regex. 

For example. If you have files like this:
- `/path/to/file.remux.mkv`
- `/path/to/fileanotherflag.mkv`
- `/path/to/file.mkv`

If you write some regex that says `^((?!remux|anotherflag|someotherstring).)*$` it will ignore all files that do not have:
"remux", "anotherflag" or "someotherstring" in their name/path.
So in the list above, only `/path/to/file.remux.mkv` and `/path/to/fileanotherflag.mkv` will be added and `/path/to/file.mkv` will be ignored.
