### ISSUE TITLE
Support image based subtitles if possible

### ISSUE THREAD

**Issue by Josh5** [Unmanic/unmanic#74]
At the moment the application cannot support image based subtitle codecs. When remuxing, subtitle streams can only be copied if they are explicitly supported by the destination container. No image based codecs are currently configured to work with the application.

You should see if there exists the possibility to copy an image based subtitle stream if the destination container supports it.
You should also force the removal of the subtitle stream if the destination container cannot support it (adding a notice in the settings pertaining to this action).

**Comment by Mushy-Snugglebites-badonkadonk** [comment]
How does Handbrake handle the subtitles then? Would looking at the way Handbrake handles subtitles help?

**Comment by Josh5** [comment]
The application has now changed. This is not an issue directly related to Unmanic any longer. If people need to support image subtitles in a destination video file, and this is not possible with the current set of plugins, a new issue should be created [here](https://github.com/Unmanic/unmanic-plugins/issues/new)
