### ISSUE TITLE
[Feature request] Ignore hidden directories.

### ISSUE THREAD

**Issue by UnR34L** [Unmanic/unmanic#80]
Hidden directories (.hidden) are a common way of excluding directories from applications.

My use case is pointing Unmanic at PLEXs DVR directory and letting Unmanic do it's thing, sadly it's doing it's thing with the '.grab' folders PLEX uses to store unfinished and still recording media.

**Comment by Josh5** [comment]
Resolved with the release of the "Path Ignore" plugin: https://github.com/Unmanic/unmanic-plugins/tree/repo/path_ignore
