### ISSUE TITLE
[Feature Request] Priority Queue

### ISSUE THREAD

**Issue by itimpi** [Unmanic/unmanic#84]
i would find it very useful if it was possible to specify 2 locations to be used for looking for items to process with one always having priority over the other when looking for the next item to process.

The Use Case for this is I would like to use the high priority queue for new items that I obtain so that I can process them before adding them to my main library.    The second queue would then be used to handle existing material that I want to convert as a background activity.

**Comment by Josh5** [comment]
This is an old request. I probably will not be adding this exact feature.

Closing this issue as It is no longer on the road map to be created and no one else seems to be developing this project
