### ISSUE TITLE
folders left behind in cache

### ISSUE THREAD

**Issue by itimpi** [Unmanic/unmanic#85]
### Description
It appears that when a conversion completes it leaves an empty folder with a name of the form:
file_conversion-*
 in the Cache path location

### Steps to Reproduce

1. Run a conversion
2. On completion look in the Cache path location

**Expected behavior:**
The folder should be removed after the converted file has been moved back to the Library path

**Actual behaviour:** 
An empty folder is left behind for each successful conversion.    Over time these start accumulating!

**Reproduces how often:**
100% of the time

### Versions
V0.0.1-beta7-0be090f

Running latest docker version hosted on Unraid OS 6.8.0-rc3 (although it has also been happening on earlier versions).

### Installation Method Used

Docker

**Comment by Apocrathia** [comment]
Can confirm that this is also leaving behind files, causing the storage device to fill up. This can happen quite rapidly on /tmp (ramdisk) drives.

**Comment by caplam** [comment]
Confirm that too. For now i manually delete emty folders.

**Comment by Geek16432** [comment]
I have a script running daily to clear these.

**Comment by dwtaylornz** [comment]
+1 here too

**Comment by dglb99** [comment]
Also, have his issue.

**Comment by Josh5** [comment]
No longer an issue. This should now be resolved as the post-processor cleans up the directories.

If this is a problem for anyone in the future, then check the logs and there will be an exception thrown preventing the post-processor from running. Submit that log as a new issue here.
