### ISSUE TITLE
Random Videos fail to convert.

### ISSUE THREAD

**Issue by clifford64** [Unmanic/unmanic#86]
Have you read the [Code of Conduct](CODE_OF_CONDUCT.md)? By filing an Issue, you are expected
to comply with it, including treating everyone with respect:

Remember that these are some guidelines, use your best judgement.

### Description

Random videos that unmanic finds to convert fail almost instantly. I have not been able to find a reason or any similarities between the files as to why these ones are failing.

### Steps to Reproduce

Not really sure how to get others to reproduce. What I have done was:
1. I noticed Unmanic was slow, so I removed the container and all data associated with it. I then recreated the docker container and manually set it back up. After it created a new database, it was much faster. I had previously had 4500+ items successfully converted in the old database. Never had a single failure. Now I have a bunch of random files failing. Other files complete successfully.

**Expected behavior:** [

Convert files or give a specific error as to why it fails.

**Actual behaviour:**

Random files fail to convert almost instantly with no error.

**Reproduces how often:**

Of about the last 300 files I put in, I would say about 20-30 have failed. They continue to retry, but still fail.

### Versions

v0.0.1-beta7~0be090f

### Installation Method Used

Docker container through docker-compose

**Comment by clifford64** [comment]
I guess this also goes along with it, it says no ffmpeg logs were collected. Not sure if it is doing this for others, but it could be useful if those were working to figure out what is going on.

**Comment by clifford64** [comment]
I think the thing in common with videos failing to convert is the videos that failed have subtitle tracks on them. I have it set to keep subtitle tracks when it converts. The subtitles are a "DVB Subtitle."

**Comment by browned** [comment]
I have this issue, not as often as you and not as quickly, with debugging on it looks like the file has converted. 

This is the last line in the conversion log.
frame=136223 fps= 15 q=-0.0 size=  852864kB time=01:34:36.38 bitrate=1230.8kbits/s speed=0.613x    

I have also had some files say success but the file size was only about 100mb. Basically it kill the file. It reports ok and plays in VLC but will stop well before the actual end of the file.

**Comment by clifford64** [comment]
After turning debugging on, the same thing is happening to me. The error log looks like it is completing successfully, but the video does not convert. Even though I have it set to not convert audio, it seems to be failing on episodes that have multiple audio tracks.

**Comment by Josh5** [comment]
This should not be an issue any longer. If it is an issue for anyone, check the submit logs with a new issue.
