### ISSUE TITLE
Videos fail to convert without errors

### ISSUE THREAD

**Issue by clifford64** [Unmanic/unmanic#91]
Have you read the [Code of Conduct](CODE_OF_CONDUCT.md)? By filing an Issue, you are expected
to comply with it, including treating everyone with respect:

Remember that these are some guidelines, use your best judgement.

### Description

Videos will fail to convert if they have special subtitles and the option to "remove subtitles" is unchecked. The examples I have are PGS and DVB subtitle files. I also have audio converting off, so it will just convert video only. Not sure if this has an affect.

### Steps to Reproduce

1. Have video with subtitles like DVB or PGS
2. Make sure "remove subtitles" is unchecked. I also have audio converting off, so it will just convert video only. Not sure if this has an affect.
3. Watch video fail to convert.

**Expected behavior:** 

I would expect that "remove subtitles" being unchecked would leave subtitles alone and just convert audio and video.

**Actual behaviour:**

Video fails to convert with no errors. Continues to reprocess and fail to convert.

**Reproduces how often:**

This seems to happen pretty consistently and then only constant is the subtitles.

### Versions

Version - v0.0.1-beta7~0be090f

Using Ubuntu 19.04 with the latest updates.

### Installation Method Used

Installed through docker-compose

### Additional Information

I also have audio set to not convert, so it is using original audio tracks and subtitles. Should be just converting Video only.

**Comment by clifford64** [comment]
For example, with debugging enabled, it shows it starts to convert, gets to about 13 minutes, fails. Then it moves onto the next one. There is not error as to why it fails, it just stops the log. The video then goes to the bottom of the queue and will try again later and generally succeed.

**Comment by aidanjt** [comment]
I ran into the same issue with remuxes, presumably because of the PGS subs.  One of the reasons I really like MKV containers is precisely so I don't have to deal with external subtitles, so it'd be nice to see this fixed.  I appreciate that PGS to srt conversion is non-trivial, but I'd be happy enough with just passing the PGS sub stream through and I can get around to the PGS to srt conversion later.

**Comment by clifford64** [comment]
I don't think it's PGS because while I haven't gotten too much content with PGS, the one time I did it have me a clear error with PGS. Whereas this is just stops mid transcode and no error. Like it makes it to a certain frame and then just stops. It marks it as a fail and puts it at the bottom of the list. Then when it gets to that item again, it transcodes successfully.

**Comment by Josh5** [comment]
This will probably be fixed when I get around to implementing image based subtitles

**Comment by Josh5** [comment]
This should not be an issue any longer. The plugins available now with Unmanic should be able to transcode video without remuxing and maintain all image subs or other data streams. If it is an issue for anyone, check the submit logs with a new issue.
